### ISSUE TITLE
Magento 2.1

### ISSUE THREAD

**Issue by Maurodev** [pagseguro/magento2#10]
É possível fazer a integração deste modulo na versão da plataforma magento 2.1 ?

**Comment by esilvajr** [comment]
É possível sim! 

Execute os comandos:

bin/magento setup:upgrade 

e depois, 
bin/magento setup:static-content:deploy pt_BR*

*Se sua loja estiver em um pacote de linguagem diferente do pt_BR substitua esse parâmetro pelo equivalente da linguagem vigente.
