### ISSUE TITLE
SyntaxError: Invalid regular expression: range out of order in character class

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#104]
Olá, 

O módulo funciona perfeitamente, porém, quando pedimos para o Magento fazer o merge dos files JS e CSS, ocorre o seguinte erro no console e o Pag Seguro não carrega no checkout

SyntaxError: Invalid regular expression: range out of order in character class

**Comment by s2it-moscou** [comment]
Bom dia @gcampedelli ! Obrigado por contribuir, poderia informar mais informações do erro que não funciona ? Alguma imagem do erro ? Qual versão do Magento/ PHP ? Pra efetuar uma validação/ simulação do erro ocorrido.

**Comment by gcampedelli** [comment]
Caro, não sei o que fazer sobre esse erro. 
Informando melhor. O Dev Docs do Magento diz para usar Minify JS quando em modo produção. 
Então, para ver o erro, você precisa ativar o Modo Produção e nas configurações ativar o Minify JS. 
No caso, o Pag Seguro não carrega no checkout em modo produção quando o Minify JS está ativado.
Imagino que seja alguma configuração faltando no Require-JS, mas não estou certa disso.
