### ISSUE TITLE
Parcelamento na página do produto não aparece

### ISSUE THREAD

**Issue by raphaelcordeiro** [pagseguro/magento2#107]
Não apresenta erro, porém, mesmo estando ativo, o parcelamento na página do produto não aparece.

**Comment by s2it-moscou** [comment]
@raphaelcordeiro Bom dia pode me passar os dados da versão do Magento, versão do PHP, alguma imagem do erro, para simulação.

**Comment by raphaelcordeiro** [comment]
Olá! Meu magento é versão 2.2.3, painel plesk, usando php versão 7.1.15. Não aparece nenhum erro, apenas não exibe o parcelamento na página do produto

**Comment by s2it-moscou** [comment]
@raphaelcordeiro Bom dia obrigado pela contribuição do erro encontrado referente há não exibição do parcelamento na página do produto, estamos validando o Plugin do Pagseguro para o módulo Magento 2.2.3 e em breve disponibilizaremos uma versão atualizada, O Pagseguro está com suporte até a versão 2.2.2 atualizada.
