### ISSUE TITLE
Cupom de Desconto

### ISSUE THREAD

**Issue by JonasPoli** [pagseguro/magento2#112]
Estamos com um problema específico que é o fato do PagSeguro ignorar o Cupom de desconto.

No exemplo reportado, estamos tentando fazer uma compra com um cupom de 10% de desconto.
O produto custa R$ 1.080,00 e o desconto a ser aplicado deve ser de R$ 108,00 (ou seja, 10%)

Aqui adicionamos o cupom de desconto na compra
![selection_143](https://user-images.githubusercontent.com/38433118/38819206-2a3fc624-4171-11e8-8df8-f5e0a3c1e95d.png)

Aqui, aparece o valor calculado da venda descontando o cupom de desconto.
Foi adicionado o frete, de R$ 33,32.
E o novo total ficou em R$ 1.005,32

Item | Valor
------------ | -------------
Produto | R$ 1.080,00
Frete |  R$ 33,32
Cupom de desconto |  **- R$ 108,00**
Total |  R$ 1.005,32

![selection_145](https://user-images.githubusercontent.com/38433118/38819219-307ff3b0-4171-11e8-96d5-d0e46bdc2e3d.png)

Valor calculado pelo PagSeguro desconsiderando o Cupom:

Item | Valor
------------ | -------------
Produto | R$ 1.080,00
Frete |  R$ 33,32
Total |  R$ 1.114,32

Aqui, O valor que o PagSeguro cobra do cliente, ignorando o valor do cupom de desconto
![selection_146](https://user-images.githubusercontent.com/38433118/38819228-338e8b52-4171-11e8-9ab7-a2ca8653e4e0.png)

Esta funcionalidade é imprescindível para desenvolvermos campanhas de Marketing.

Estamos utilizando o Magento 2.1.9 e o módulo do PagSeguro 3.3.0.
Existe alguma previsão dessa funcionalidade funcionar?

**Comment by s2it-moscou** [comment]
Boa Tarde @JonasPoli obrigado pelo contato, de acordo com o problema relatado fiz a simulação do problema em ambiente Sandbox utilizando o módulo Magento 2.19 e Plugin Pagseguro versão 4.2.0 atualizado e disponível para download: https://github.com/pagseguro/magento2 e foi efetuado o desconto corretamente do produto/ produtos com 10% de desconto nos Checkout Padrão, Lightbox e Transparente. Fiz a configuração desse desconto na Criando um novo desconto em Marketing > Cart Price Rules e configurando nas condições.

Checkout Padrão:
![1](https://user-images.githubusercontent.com/25645558/39015306-664b37dc-43f3-11e8-91b4-41d546d939e3.png)
![2](https://user-images.githubusercontent.com/25645558/39015313-6b283b42-43f3-11e8-858e-e09507f4ef94.png)
![3](https://user-images.githubusercontent.com/25645558/39015317-6de00694-43f3-11e8-9ded-3898efabf87f.png)
![4](https://user-images.githubusercontent.com/25645558/39015321-6ffa0dd0-43f3-11e8-8fd9-ed09c3bc820e.png)
Lightbox:
![lightbox](https://user-images.githubusercontent.com/25645558/39015338-7ac97624-43f3-11e8-9ac2-86cc98461c19.png)
![lightbox_2](https://user-images.githubusercontent.com/25645558/39015345-7fdd19cc-43f3-11e8-911a-9596432e9f83.png)

Peço por favor que valide esse problema relatado no Plugin atualizado 4.2.0 que é  última versão que simulei e caso necessite pode enviar mensagem novamente.

**Comment by JonasPoli** [comment]
Bom dia, Recebemos.

Vou analisar.


Atenciosamente,



*Jonas Poli*
Diretor Técnico
*Wab Agência Digital*
Tel: (16) 3332-7798
Cel: (16) 98179-1110
jonas@wab.com.br


Em 19 de abril de 2018 17:11, s2it-moscou <notifications@github.com>
escreveu:

**Comment by s2it-moscou** [comment]
Boa Tarde @JonasPoli ainda está ocorrendo o problema ? Irei fechar a ISSUE, caso necessário pode reabrir a ISSUE novamente ! Obrigado pelo contato com o Pagseguro.
