### ISSUE TITLE
Nao funciona com minify de js ativo

### ISSUE THREAD

**Issue by lcsbaroni** [pagseguro/magento2#115]
Com a opção de minificar e mesclar js o modulo não mostra as opções de pagamento no checkout.
Isso ocorre porque o magento coloca o sufixo ".min" em todos os arquivos js, inclusive os externos. Assim os arquivos abaixo não são encontrados:
https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.min.js
https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.min.js

O arquivo existe se retirar o ".min". Desabilitando o minify no admin também funciona.

Temos 2 possíveis soluções:
1 - Disponibilizar os arquivos acima com o sufixo ".min"
2 - Adicionar os arquivos na lista de exclusão de minify do modulo (etc/config.xml). Ex:
```
        <dev>
            <js>
                <minify_exclude>
                    jstoexclude
                    jstoexclude
                </minify_exclude>
            </js>
        </dev>

**Comment by wubuyun** [comment]
e como faz isso amigo, tentei e nada..
tem algum exemplo...

**Comment by katiakweb** [comment]
Em qual versão do Magento estás implementando? Qual versão do PHP?

**Comment by wubuyun** [comment]
magento 2.2.6
php 7.1
ta funcionando somento pagamento redirecionado. transparente preciso tira min.js

**Comment by wubuyun** [comment]
> Em qual versão do Magento estás implementando? Qual versão do PHP?
magento 2.2.6
php 7.1
ta funcionando somento pagamento redirecionado. transparente preciso tira min.js

**Comment by katiakweb** [comment]
Me diz direitinho o que vc fez, quero tentar aqui... estou testando nesta versão do magento tb. Obrigada!

**Comment by wubuyun** [comment]
qual a sua configuracao

**Comment by katiakweb** [comment]
> qual a sua configuracao
Nginx Server, Magento 2.2.4 - PHP 7.0.30

**Comment by katiakweb** [comment]
@wubuyun que mágica foi essa? Conseguiu no Magento 2.2.6! Tirando meu chapéu pra vc!

**Comment by gabrielmazaia** [comment]
Alguém teve sorte nesta dica dele?
