### ISSUE TITLE
PRoblema ao tentar acessar o Pedido de Venda

### ISSUE THREAD

**Issue by flaviobecker9** [pagseguro/magento2#116]
Após finalizar o Pedido vou no Backend e quando tento acessar da o seguinte erro:

A tela da o seguinte erro:
Exception #0 (Exception): Notice: Undefined index: label in /vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Select.php on line 75

A seguinte mensagem no log de erro do sistema aparece:
Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively

No Log do Pagseguro não aparece nada. 
Quando desabilito o modulo Pagseguro consigo acessar o Pedido normalmente.

Meu Magento é o 2.2.2

**Comment by andrecristiani** [comment]
@flaviobecker9 aparentemente parece ser um bug. Vamos trabalhar na correção.

Obrigado pela contribuição!

**Comment by danilolima** [comment]
Estou com o mesmo problema @flaviobecker9. Conseguiu contornar o problema de alguma forma?

**Comment by cybbrw** [comment]
@flaviobecker9 conseguiu alguma correção? @danilolima conseguiu corrigir esse bug ?

**Comment by thiagogalvao** [comment]
também tive este problema na versão 2.2.5 e não consegui resolver.

**Comment by muquilu** [comment]
https://github.com/magento/magento2/issues/4145

Altera a classe no core do magento ou faz um plugin pra sobrescrever o helper... eu como estava com pressa alterei direto no core...

**Comment by muquilu** [comment]
Problem can be resolved by adding the following line Magento\Payment\Helper\Data:

public function getPaymentMethodList($sorted = true, $asLabelValue = false, $withGroups = false, $store = null)
    {
        $methods = [];
        $groups = [];
        $groupRelations = [];

        foreach ($this->getPaymentMethods() as $code => $data) {
            if (isset($data['title'])) {
                $methods[$code] = $data['title'];
            } else {
                $methods[$code] = $this->getMethodInstance($code)->getConfigData('title', $store);
            }
            if ($asLabelValue && $withGroups && isset($data['group'])) {
                $groupRelations[$code] = $data['group'];
            }
        }
        if ($asLabelValue && $withGroups) {
            $groups = $this->_paymentConfig->getGroups();
            foreach ($groups as $code => $title) {
                $methods[$code] = $title;
            }
        }
        if ($sorted) {
            asort($methods);
        }
        if ($asLabelValue) {
            $labelValues = [];
            foreach ($methods as $code => $title) {
                $labelValues[$code] = [];
            }
            foreach ($methods as $code => $title) {
                if (isset($groups[$code])) {
                    $labelValues[$code]['label'] = $title;
                } elseif (isset($groupRelations[$code])) {
                    unset($labelValues[$code]);
                    // Add the line below - adds a label to the payment options' group.
                    $labelValues[$groupRelations[$code]]['label'] = $groupRelations[$code];
                    $labelValues[$groupRelations[$code]]['value'][$code] = ['value' => $code, 'label' => $title];
                } else {
                    $labelValues[$code] = ['value' => $code, 'label' => $title];
                }
            }
            return $labelValues;
        }

        return $methods;
    }

**Comment by lucianoalbis** [comment]
Passei por esse mesmo problema com o Magento 2.2.0 e enquanto o PagSeguro não disponibiliza uma fix uma solução temporária seria modificar a método "getPaymentMethodList" ou criar um override classe Select inserindo uma validação no metodo "getHtml".

Obs: Não é recomendado mexer em código standard pois ao rodar alguma atualização de dependencia o código se perdera.

**Comment by raphaelcordeiro** [comment]
Estou com esse problema! Como resolveram? O que alteraram no código pra ficar ok?

**Comment by lucianoalbis** [comment]
Olá,

Como descrito no comentário antes do seu, acabei realizando a operação descrita e aí funcionou, porém como falei, não é recomendado mexer em código standard, mas como era urgente e o PagSeguro não fez nada. Tenta aí essa solução e me fala se deu certo,caso contrário tentamos outra coisa.
