### ISSUE TITLE
Finaliza a compra, mas não gera o pagamento.

### ISSUE THREAD

**Issue by leogold** [pagseguro/magento2#117]
Mensagem no checkout.
Desculpe, infelizmente, houve um erro durante o checkout.Entre em contato com o administrador da loja, se o problema persistir.
--

debug.log (Com debug ativo) Dei permissão chmod 777 -R var/ pub/
[2018-05-24 17:42:36] main.ERROR: [Uol PagSeguro Module][Payment Error] Warning: file_put_contents(var/log/pagseguro.log): failed to open stream: No such file or directory in /h$ in /home/inverto/m2/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Log/Logger.php on line 202 [] []
(Sem debug ativo)
[2018-05-24 17:50:16] main.ERROR: [Uol PagSeguro Module][Payment Error] Invalid document [] []

**Comment by leogold** [comment]
Não sei para onde ir.... Obrigado!

**Comment by katiakweb** [comment]
Eu fui nesta direção: https://github.com/Bleez/Pagseguro
Ainda em testes...

**Comment by sergiomendonca** [comment]
Katiak, o Bleez é cheio de bugs...tem muitos bugs mesmo. Além de ser feito por terceiros, vai reclamar com quem se der problema?  O programador não vai ficar atualizando o software, sinceramente ao meu ver se não for oficial e tiver integração externa tem que pensar duas vezes...

**Comment by raphaelcordeiro** [comment]
Conseguiram resolver o problema?

**Comment by sergiomendonca** [comment]
O meu caso era ter utilizado um plugin para quebrar o endereco em 4 campos, todos deveriam ser obrigatorios, depois disso funcionou, mas meu erro parece ser diferente da pessoa acima. Eu utilizo a versão 2.1.9 e não tive mais esse tipo de problema.
