### ISSUE TITLE
erro instalacao magento2.2.4

### ISSUE THREAD

**Issue by marcelowu** [pagseguro/magento2#119]
![default](https://user-images.githubusercontent.com/30912144/40760448-40c0b54c-646d-11e8-9e71-56d4001cc0a1.PNG)

**Comment by katiakweb** [comment]
É a versão de PHP que vc está usando amigo... que eu saiba acima de 7.0 dá problema... me corrijam se eu estiver errada.

**Comment by marcelowu** [comment]
Olá, uma solução provisória é forçar o composer a ignorar essa verificação, adicionando "--ignore-platform-reqs". Você coloca essa dependencia no seu composer.json e roda o comando:
composer update --ignore-platform-reqs, ou um fork no projeto e altera direto no composer.json
https://github.com/pagseguro/magento2/issues/84

**Comment by marcelowu** [comment]
esta funcionando direidinho no magento 2.2.4 php 7.1
