### ISSUE TITLE
Problemas ao Instalar e Funcionar no Magento 2.1.1

### ISSUE THREAD

**Issue by ramonvic** [pagseguro/magento2#12]
Tive alguns problemas com a instalação dessa biblioteca, enumerando:
- A instalação padrão: "composer require pagseguro/magento2", não funcionou. Só consegui a instalação clonando o Repositório dentro da pasta `app/code/UOL/PagSeguro`

- Após a instalação o Módulo não funcionou, como sou iniciante no magento2, nao sei se o erro está no módulo ou na minha instalação.
Estou tentando utilizar o checkout transparente, e recebo a mesnagem abaixo, quando vou testar o checkout.

`{
    "message": "Property \"Title\" does not have corresponding setter in class \"Magento\\Quote\\Api\\Data\\PaymentInterface\".",
    "trace": "
    #0 Store_Path/vendor\/magento\/framework\/Reflection\/NameFinder.php(59): Magento\\Framework\\Reflection\\NameFinder->findAccessorMethodName(Object(Zend\\Code\\Reflection\\ClassReflection), 'Title', 'getTitle', 'isTitle')
    #1 Store_Path/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(158): Magento\\Framework\\Reflection\\NameFinder->getGetterMethodName(Object(Zend\\Code\\Reflection\\ClassReflection), 'Title')
    #2 Store_Path/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(322): Magento\\Framework\\Webapi\\ServiceInputProcessor->_createFromArray('Magento\\\\Quote\\\\A...', Array)
    #3 Store_Path/vendor\/magento\/framework\/Webapi\/ServiceInputProcessor.php(119): Magento\\Framework\\Webapi\\ServiceInputProcessor->convertValue(Array, 'Magento\\\\Quote\\\\A...')
    #4 Store_Path/vendor\/magento\/module-webapi\/Controller\/Rest\/InputParamsResolver.php(101): Magento\\Framework\\Webapi\\ServiceInputProcessor->process('Magento\\\\Checkou...', 'savePaymentInfo...', Array)
    #5 Store_Path/vendor\/magento\/module-webapi\/Controller\/Rest.php(299): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()
    #6 Store_Path/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()
    #7 Store_Path/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
    #8 Store_Path/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
    #9 Store_Path/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()
    #10 Store_Path/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))
    #11 {main}"
}`

**Comment by gabriellucius** [comment]
Olá @ramonvic.

Primeiramente, desculpe a demora para lhe responder. Eu acredito que estes problemas de instalação tenham sido resolvidor aqui https://github.com/pagseguro/magento2/issues/15

**Comment by rafaelrocha007** [comment]
Erro ao finalizar compra persiste: 
> Property "Title" does not have corresponding setter in class "Magento\Quote\Api\Data\PaymentInterface".

Pude notar que existe o metodo `setTitle( )` na `PaymentMethodInterface`, mas sou iniciante no Magento2 e não consegui uma solução.

**Comment by ramonvic** [comment]
@rafaelcostarocha O que fiz pra conseguir "burlar" esse erro, foi uma alteração direto no renderer do da biblioteca, como não sou desenvolvedor magento, não tenho os conhecimentos pra saber o porque de acontecer esse erro, mais basicamente o que fiz foi:
Sobrescrevi o arquivo `UOL_Pagseguro/web/js/view/payment/method-renderer/payment-method.js`.
na linha 64:
```javascript
})).done(function () {
                        $.when(placeOrder(paymentData, messageContainer)).done(function () {
```
Forcei a remoção da chave titulo do `paymentData`

```javascript
})).done(function () {
                    delete paymentData['title'];
                    $.when(placeOrder(paymentData, messageContainer)).done(function () {
```

Dessa forma não tive mais esse erro, porém não sei se isso implica em algum outro erro, como disse não tenho os conhecimentos para dizer.

De qualquer forma corrigi dessa forma.

**Comment by rafaelrocha007** [comment]
@ramonvic Eu também não sou desenvolvedor Magento, esse é meu primeiro contato com a ferramenta. Mas mto obrigado pelo feedback, já ajudou demais. Eu comecei a usar o lightbox para fazer os testes e parece ser muito mais estável do que o Checkout Transparente.

**Comment by LeartPinheiro** [comment]
Me perdoem a ignorância, mas onde ficaria o UOL_Pagseguro/web/js/view/payment/method-renderer/payment-method.js?

**Comment by ramonvic** [comment]
@Fleartype Você deve copiar o arquivo que está dentro de 
`vendor/pagseguro/magento2/view/frontend/web/js/view/payment/method-renderer/payment-method.js`
para:
`app/design/frontend/<Vendor>/<Theme>/UOL_Pagseguro/web/js/view/payment/method-renderer/payment-method.js`

Com isso o magento carregará o arquivo que está dentro do seu tema, e não o do pagseguro.

**Comment by vlfreitas** [comment]
@ramonvic implementei o que você disse e realizei testes, aparentemente não ocorreram erros. Vamos atualizar aqui. Se houver qualquer erro por gentileza avise-nos. Obrigado
