### ISSUE TITLE
Não funciona no Magento 2.2.5

### ISSUE THREAD

**Issue by josneyr** [pagseguro/magento2#122]
Qual a previsão para sair a nova versão compatível com a 2.2.5?

**Comment by thiagovidal** [comment]
Ta complicado esse pagseguro no magento 2. Já estava na hora ao menos de funcionar com php 7.1+

**Comment by katiakweb** [comment]
Eu desisti do PagSeguro por isso! Haja paciência ficar fazendo gambiarra para este módulo funcionar! Total descaso com a gente, agora só pensam em vender maquininha! estou usando o Moip e estou gostando bastante. Dá uma olhada, os valores cobrados são ligeiramente mais baratos no Moip. Ah, e estou encantada com o suporte do Moip! (Não estou ganhando nada para citar o serviço, mas faço questão de dizer que já temos outra opção sem ficar quebrando a cabeça! E com checkout transparente, o que é melhor ainda!)

**Comment by thiagovidal** [comment]
@katiakweb é vou conversar com meu cliente sobre a possibilidade de trocar para outro gateway pq pagseguro ta osso. Qual versão do magento vc esta usando? e a versão do php? Agradeço se puder me ajudar com estas informações.

**Comment by josneyr** [comment]
Pelo que notei, tem que ficar no máximo na versão 2.2.1 e PHP 7.0.30, porque há problemas com módulos de one checkout - checkout como visitante e de campos para o Brasil (cpf, endereço etc). O melhor é criar a loja e sempre ter um ambiente de testes para fazer upgrades e ver se todas as funcionalidades estão funcionando corretamente.

Mas sobre esses gateways de pagamento é inadmissível a pagseguro, cielo, moip, pagar.me, mundipagg etc não estar sempre atualizado para a última versão. Pois são "sócios" cobrando alta porcentagem sobre as vendas, quando na verdade deveriam cobrar só uma taxa sobre o serviço. O mínimo que podem fazer é manter seus gateways atualizados para os e-commerces mais utilizados:  Magento (1 e 2) e Woocommerce.

**Comment by katiakweb** [comment]
Estou usando a versão 2.2.4 do Magento, com PHP 7.0.30, mas logo vou testar no Magento 2.2.5, estou configurando o servidor já. Quando testar posso dar maiores informações.
O Moip também oferece um ótimo suporte via Chat, me ajudaram na primeira instalação. Diz pro seu cliente conferir as tarifas, a princípio parece que o Moip é mais caro, mas na hora de comparar, é coisa de centavos... já tenho vários clientes que trocaram para o Moip e estão gostando.

**Comment by cybbrw** [comment]
@katiakweb também estou levando dois clientes para o Moip. Suporte premium, acredito que é porque o Moip é uma startup, nasceu com a tecnologia como produto fim. Já o PagSeguro é um produto UOL. O @pagseguromaster  tem que tomar umas aulas de gestão com o Paypal: Módulo integrado, tudo funciona, suporte do time de DEV 100% rápido (questão de minutos e qualquer bug é corrigido). 

O MOIP está 100% funcional conosco: Magento 2.2.4. Paypal idem. 

Vamos atualizar alguns clientes no final deste mês (2.2.5)

**Comment by thiagovidal** [comment]
Infelizmente meu cliente não quer ir para o Moip por conta das taxas. Vou ter que quebrar a cabeça com este modulo do paseguro. Vamos movimentar este tópico que sabe eles se pronunciam.

**Comment by josneyr** [comment]
A Cielo é bem em conta, mas parece não ter anti-fraude, alguém sabe?
Tem plugins free que ainda não sei se estão funcionando:
https://github.com/setor7soft/magento2-cielo

**Comment by katiakweb** [comment]
@thiagovidal, diga para o seu cliente conferir as taxas cobradas usando como exemplo uma compra de R$ 100,00 em 3x com parcelamento com custas para o comprador em ambos os gateways de pagamento. A diferença é de centavos no final... Neste exemplo que eu dei, o vendedor recebe R$ 88,91 no PagSeguro e R$ 88,82 no Moip... O que o usuário não se dá conta são que as taxas de parcelamento do PagSeguro são bem mais altas... isso dá uma grande diferença na conta final... O Moip também oferece a opção de receber parcelado, (no meu exemplo, se o cliente recebe em 3x, conforme o pagador efetua os pagamentos) o valor a receber é de R$ 93,82. Sugira a ele que crie uma conta no Moip e faça simulações. Eu não estou recebendo comissão do Moip para citá-los, mas como também tenho loja online, sei como o vendedor se sente e posso garantir que acho que vale a pena, pois devido aos inúmeros problemas na finalização da compra do PagSeguro, acho que mais vale usar um gateway que te oferece mais suporte, pois no final, isso garante o sucesso na hora do cliente finalizar a compra, o que vale os centavos da diferença, na minha opinião de vendedora...

**Comment by thiagovidal** [comment]
@katiakweb muito bom ter um parecer de quem utiliza o serviço. Encaminhei sei comentário para meu cliente. Desculpe não ter solicitado antes; porem achei super pertinente. Muito obrigado pela sua ajuda. ;)

**Comment by katiakweb** [comment]
@cybbrw Concordo 100% com você! Pra ter ideia de quão desemparados estamos pelo PagSeguro, estamos aqui, falando sobre outros serviços de pagamento eles nem se pronunciam, kkkkkkkk.

**Comment by gcampedelli** [comment]
Eu fiz um outro módulo para PagSeguro

**Comment by katiakweb** [comment]
E aí, vai disponibilizar para nós @gcampedelli ? Quanto vai ser? Funciona no modo transparente? Até que versão de Magento e PHP funciona o seu módulo?

**Comment by gcampedelli** [comment]
É php 7. Funciona transparente e boleto, e tem umas configurações. Eu instalo e cobro e faço as alterações necessárias no checkout. E funciona no Magento 2.x até o 2.2.6. O que eu disponibilizei para a comunidade foi o Desconto com base no Pagamento nas regras do carrinho. Tá lá no meu perfil

**Comment by thiagovidal** [comment]
Bom eu dei um jeito aqui e consegui fazer funcionar no 2.2.4 e no 2.2.5.... só não me lembro mais o que eu fiz para funcionar.... mas ta rodando bem.

**Comment by ianitsky** [comment]
Eu fiz uma versão para corrigir vários bugs. E estou sempre de olho, esperando alguma alteração aqui para incrementar no meu e deixar sempre atualizado.

https://github.com/ianitsky/pagseguro-magento2

Espero que eles comecem a aceitar os PRs que têm aqui, ou pelo menos dar mais atenção às issues para podermos voltar ao projeto principal. :'(

**Comment by blopa** [comment]
@ianitsky obrigado por compartilhar. Essa versao funciona com o Magento 2.2.7 e/ou 2.3? Obrigado

**Comment by ianitsky** [comment]
2.3 precisa ser testado, minha versão é a 2.2.7. Mas irei fazer isso

**Comment by thiagogalvao** [comment]
Boa galera!!! Obrigado pela iniciativa.
Vou testar no 2.3 por estes dias e reporto por aqui.

**Comment by blopa** [comment]
@ianitsky Instalei na minha loja 2.2.7, porém estou recebendo esse erro:

1 exception(s):
Exception #0 (Exception): CURL can't connect: Could not resolve host: https

Exception #0 (Exception): CURL can't connect: Could not resolve host: https
#0 /var/www/magento/htdocs/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Http.php(112): PagSeguro\Resources\Http->curlConnection('POST', 'https:///v2/ses...', 20, 'UTF-8', NULL)

Alguma idéia do que pode ser?

**Comment by ianitsky** [comment]
Olha man,

tem cara de ser configuração, por causa desse carinha aqui:  'https://
/v2/ses...'
Não tem o host.

Mas não sei quando isso está acontecendo. Se tivesse o trace completo
ficaria mais fácil.

Douglas Borella Ianitsky


Em seg, 28 de jan de 2019 às 19:23, Pablo Benmaman <notifications@github.com>
escreveu:

**Comment by blopa** [comment]
@ianitsky Realmente foi falta de configuracao. Eu configurei no store view, e nao no global. Depois de botar no global parou de dar esse erro. Vou continuar com os testes, obrigado :D

**Comment by blopa** [comment]
Estou com um novo problema, não consigo finalizar o pedido com o pagamento PagSeguro Padrão. E parece que mesmo que eu escolha "Padrão", ele sempre tenta carregar o lightbox.

O checkout redireciona para minhaloja.com.br/pagseguro/payment/failure

Não tem nada nos logs :( nem mesmo o log do PagSeguro, mesmo eu tendo ativado.

**Comment by blopa** [comment]
Esse é o erro que aparece no meu log do nginx:

```
2019/01/30 17:58:07 [error] 22067#22067: *10487 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to UOL\PagSeguro\Model\PaymentMethod::__construct() must be an instance of Magento\Sales\Model\Order, instance of Magento\Checkout\Model\Session\Interceptor given, called in /var/www/magento/htdocs/app/code/UOL/PagSeguro/Controller/Payment/Checkout.php on line 61 and defined in /var/www/magento/htdocs/app/code/UOL/PagSeguro/Model/PaymentMethod.php:61
Stack trace:
#0 /var/www/magento/htdocs/app/code/UOL/PagSeguro/Controller/Payment/Checkout.php(61): UOL\PagSeguro\Model\PaymentMethod->__construct(Object(Magento\Framework\App\Config), Object(Magento\Checkout\Model\Session\Interceptor), Object(Magento\Directory\Model\CountryInformationAcquirer), Object(Magento\Framework\Module\ModuleList))
#1 /var/www/magento/htdocs/generated/code/UOL/PagSeguro/Controller/Payment/Checkout/Interceptor.php(14): UOL\PagSeguro\Controller\Payment\Checkout->__construct(Object(Magento\Framework\App\Action\Context), Object(Magento\Framework\View\Result\PageFactory))" while reading response header from upstream, client: 77.166.192.161, server: localhost.com.br, request: "GET /pagseguro/payment/checkout/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "localhost.com.br", referrer: "https://localhost.com.br/checkout/"
```

**Comment by ianitsky** [comment]
@blopa, vamos utilizar as issues lá no meu projeto, para não sujar aqui:

https://github.com/ianitsky/pagseguro-magento2/issues/1
