### ISSUE TITLE
PAGAMENTOS FREQUENTEMENTE CANCELADOS ANTES DE IREM PARA O PAGSEGURO

### ISSUE THREAD

**Issue by sergiomendonca** [pagseguro/magento2#124]
O PLUGIN APRESENTA UM DEFEITO ONDE FREQUENTEMENTE O PEDIDO É CANCELADO ANTES DE IR PARA O PAGSEGURO. EM CADA 10 PEDIDOS, 5 ACONTECEM ISSO.

OBS: COLOQUEI XXXX PARA NAO EXIBIR OS DADOS DO CLIENTE.

SEGUE O LOG DO PAGSEGURO:

------- ERRO---------------------
.....shippingAddressRequired":"true","shippingCost":"0.00","shippingAddressStreet":"xxxx","shippingAddressNumber":"491","shippingAddressComplement":"xxxx","shippingAddressCity":"XXXX","shippingAddressState":"RJ","shippingAddressDistrict":"","shippingAddressPostalCode":"xxxxx","shippingAddressCountry":"Brasil","creditCardToken":"XXXXXX"}
15/09/2018 10:57:30 PagSeguro.DirectPayment.CreditCard[error]: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53029</code><message>shipping address district is required.</message></error><error><code>53060</code><message>billing address district is required.</message></error></errors>
------- ERRO---------------------

ESSE PROBLEMA ACONTECE FREQUENTEMENTE, ALGUNS CLIENTES PASSAM, OUTROS NÃO.

O PEDIDO NEM APARECE NO PAGSEGURO COMO CANCELADO, SOMENTE NO MAGENTO APARECE...

**Comment by sergiomendonca** [comment]
VERSAO: MAGENTO 2.1.9

**Comment by wubuyun** [comment]
53029shipping address district is required. 
campo bairro faltando..
