### ISSUE TITLE
Não funciona com o PHP 7.2.14 e Magento 2.3.0

### ISSUE THREAD

**Issue by zeroskullx** [pagseguro/magento2#129]
Pego este erro no composer...
[InvalidArgumentException]
  Package pagseguro/magento2 at version  has a PHP requirement incompatible with your PHP version (7.2.14)

**Comment by geekcom** [comment]
@zeroskullx o módulo Magento2/PagSeguro funciona apenas até o PHP 7.1, observe composer.json.
`"php": "~5.5.0|~5.6.0|~7.0.0",`

**Comment by zeroskullx** [comment]
Vdd, esqueci de perguntar se tem algum plano de sair para php 7.2.* . Tentei usar o magento 2.3.0 no PHP 7.0.33 e pego alguns erros no magento. e segundo a doc do magento o minimo é 7.0.2(mas isso já é bug do magento e não do PSM2). Enfim, testei o PSM2 no php7.1 e tb não funciona, erro de incompatibilidade. observando o composer.json php:  "~5.5.0|~5.6.0|~7.0.0" acredito que o maximo é 7.0.0.

**Comment by geekcom** [comment]
Não sei  dizer se existem planos para nova versão, como está "resolvido" acho que pode fechar a issue não?

**Comment by zeroskullx** [comment]
Resolvido não está, né? Mas como é impossivel continuar já que a equipe não busca melhorar e vive na tecnologia absoleta, a gente tenta buscar versões paliativa. Como é impossivel usar instalação manual vcs deveriam tirar esse "treco" de php versão e deixar >= 5.5.0... FIM

**Comment by zeroskullx** [comment]
Usei essa dica #119 e consegui instalar no magento 2.3. Vou fazer alguns teste e posto o resultado depois, mesmo pegando um 'avizinho básico' "phpunit/phpunit-mock-objects is abandoned"

**Comment by zeroskullx** [comment]
Tudo OK; só resta testar com venda real... rs 
Vlw @geekcom pelo feedback e pode fechar esse issue!

**Comment by geekcom** [comment]
Não tenho persmissão de fechar issues @zeroskullx , podemos esperar alguém fechar ou vc mesmo pode

**Comment by Verguetz** [comment]
> 
> 
> Tudo OK; só resta testar com venda real... rs
> Vlw @geekcom pelo feedback e pode fechar esse issue!

Opa, houve algum problema apos a instalacao, ou rodou normal mesmo com a vrsao requerida pelo magento 2.3 ser superior?
