### ISSUE TITLE
Autoload error: 'UOL_PagSeguro' component already exists

### ISSUE THREAD

**Issue by henriqueneves** [pagseguro/magento2#13]
Meu Deus alguém me ajuda por favor kkkkkkkk
É o seguinte, estava com um sistema finalizado.. só que o módulo não funcionava de jeito nenhum! Ficava me dando o seguinte erro na hora de finalizar a compra pelo PagSeguro: 

> main.CRITICAL: LogicException: Property "Title" does not have corresponding setter in class "Magento\Quote\Api\Data\PaymentInterface". in /home/basican/public_html/vendor/magento/framework/Reflection/NameFinder.php:100

Então, para testes, baixei o Magento 2.0 e 2.1 novamente e configurei-os do zero. Logo depois de instala-los fui instalar o PagSeguro.
Ao executar: 
    composer require pagseguro/magento2
Obtive um erro falando que o módulo não tinha suporte "alpha" para essa versão que eu estava utilizando. Li uma solução na internet que me orientava trocar no arquivo composer.json a linha min-stability para "dev". Fiz isso e o comando funcionou.
Ao executar: php bin/magento setup:upgrade obtenho o seguinte erro:
Autoload error: 'UOL_PagSeguro' component already exists

Lembro que da primeira vez que instalei deu esse erro também. Para solucionar apaguei alguns arquivos.. O que possivelmente veio a causar os erros descritos no começo deste.

Alguém sabe o que pode ser? Prazo ta tão curto, não tem nd sobre na net :/

**Comment by marcioshimoda** [comment]
@henrique1265 .... é só remover a pasta UOL em app\code e tentar novamente.

**Comment by lcsbaroni** [comment]
remover a pasta app/code/Uol vai fazer com que esse erro pare, porém é inviável ter que apagar a pasta manualmente após um deploy. O composer que está configurado errado.

Além disso ao rodar o di:compile da o seguinte erro:
Fatal error:  Class UOL\PagSeguro\Controller\Direct contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Magento\Framework\App\ActionInterface::execute) in /var/www/miniaturadeheroi/vendor/pagseguro/magento2/Controller/Direct.php on line 27
Segmentation fault (core dumped) [] []

O que impossibilita rodar o comando:
php bin/magento deploy:mode:set production

Outro problema que é necessário incluir outra lib no composer
"pagseguro/pagseguro-php-sdk": "3.0.0"

**Comment by gsc-dev** [comment]
Olá,
Existe alguma diferença entre a pasta app/code e vendor? A primeira seria mais recente, com bug fixes?

**Comment by lcsbaroni** [comment]
Sim, a pasta vendor é criada pelo composer, o gerenciador de dependências do PHP. A configuração no composer estava errada e com isso o código estava duplicado, na pasta vendor e dentro do contexto do magento "app/code"

**Comment by ghost** [comment]
@henriqueneves Seu problema foi resolvido ? Caso já foi resolvido! irei encerrar essa ISSUE ! Qualquer dúvida envie mensagem novamente !

**Comment by henriqueneves** [comment]
Problema resolvido. Consegui realizando o proposto pelo amigo lcsbaroni.
