### ISSUE TITLE
PagSeguro no Magento 2.1.9 está bugando o /checkout/

### ISSUE THREAD

**Issue by gabrielmazaia** [pagseguro/magento2#130]
Estou tendo problemas em validar o token, depois do novo formato do PagSeguro, que inclui caracteres em lowercase e traços. 

Também quando estou ativando o módulo meu checkout nem carrega e quando carrega fica em loading infinito, quando desabilito o módulo ele funciona rápidamente.

**Comment by thiagogalvao** [comment]
Fala man! 
Configuraste o modulo com o token do sandbox no admin do magento? 
Tive problemas de crash no checkout porque estava com o token errado.

Boa sorte!

**Comment by gabrielmazaia** [comment]
Então eu fiz a configuração com o sandbox, quando a loja estava em desenvolvimento, mas quando a loja foi ao ar, modifiquei o token no modo de produção mesmo, também achei que havia feito isto, mas infelizmente não foi isso.

________________________________
De: Thiago <notifications@github.com>
Enviado: terça-feira, 21 de maio de 2019 20:06
Para: pagseguro/magento2
Cc: Gabriel Antonio; Author
Assunto: Re: [pagseguro/magento2] PagSeguro no Magento 2.1.9 está bugando o /checkout/ (#130)


Fala man!
Configuraste o modulo com o token do sandbox no admin do magento?
Tive problemas de crash no checkout porque estava com o token errado.

Boa sorte!

**Comment by thiagogalvao** [comment]
A tua instalação do magento as tabelas da base de dados estão com prefixos? também tive problemas com isso.

**Comment by gabrielmazaia** [comment]
Desculpa minha ignorância, mas como posso identificar isto?

Em 27 de mai de 2019 17:42, Thiago <notifications@github.com> escreveu:

A tua instalação do magento as tabelas da base de dados estão com prefixos? também tive problemas com isso.

**Comment by thiagogalvao** [comment]
Verifca no phpmyadmin do seu servidor, caso os nomes das tabelas iniciem com xpto_nomedatabela o "xpto_" é o prefixo. Neste módulo do pagseguro tem umas instruções SQL que são executadas sem levar em consideração estes prefixos.

**Comment by sergiomendonca** [comment]
Realmente, o magento 2.1.9 padrão não tem problemas com este modulo. Só no navegador firefox as validações ficam bugadas, mas a correção para isso é simples.
