### ISSUE TITLE
Nada acontece ao clicar em finalizar compra

### ISSUE THREAD

**Issue by tangzin** [pagseguro/magento2#133]
Beleza pessoal?
Estou há mais de um mês tentando resolver este problema.

O problema número 01 é; mesmo eu colocando SIM na opção para gravar log do pagseguro, ele não gera nenhum arquivo. Então não consigo saber exatamente o que está acontecendo para que o pedido não seja concluído.

O erro principal é que simplesmente ao clicar em Finalizar Compra, não redireciona para o pagseguro, ou não abre a página para escolher o método, no caso do Checkout transparente habilitado.

Agradeceria qualquer tipo de ajuda.

Abraços

**Comment by AbnerSam** [comment]
Hablita o Log, limpa o cache e tenta novamente pra gerar o erro.
