### ISSUE TITLE
Erro instalando via Composer - PHP7.3

### ISSUE THREAD

**Issue by fabiofbra** [pagseguro/magento2#136]
PHP 7.3
Composer V2

Tentando instalar recebo as mensagens:

composer require pagseguro/magento2

The "magento/magento-composer-installer" plugin was skipped because it requires                                      a Plugin API version ("^1.0") that does not match your Composer installation ("2                                     .0.0"). You may need to run composer update with the "--no-plugins" option.
The "magento/inventory-composer-installer" plugin was skipped because it require                                     s a Plugin API version ("^1.1") that does not match your Composer installation (                                     "2.0.0"). You may need to run composer update with the "--no-plugins" option.

 [InvalidArgumentException]
  Package pagseguro/magento2 at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

Quando executo com o --no-plugins, apenas o erro aparece:
[InvalidArgumentException]
  Package pagseguro/magento2 at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

Alguém já passou por isso? Sugestões?
Obrigado

**Comment by adrielmsantos** [comment]
Use o composer v1

A versão 2 não é compatível
