### ISSUE TITLE
Url de Notificação

### ISSUE THREAD

**Issue by Emers0n** [pagseguro/magento2#14]
Gostaria de saber como informar a url de notificação, para sincronizar a situação dos pedidos.
att

**Comment by lcsbaroni** [comment]
A url para notificação é /pagseguro/notification/response. Você deve colocar isso na configuração do modulo

**Comment by gabriellucius** [comment]
@Emers0n é como o @lcsbaroni  comentou, é o url da sua loja +  /pagseguro/notification/response

**Comment by pguedesbr** [comment]
Porque esse valor não já vem preenchido?

**Comment by gabriellucius** [comment]
Adicionamos a url padrão para notificação na branch master no PR https://github.com/pagseguro/magento2/pull/58

**Comment by s2it-moscou** [comment]
Melhoria aplicada, caso o comportamento persista abriremos novamente a issue.
