### ISSUE TITLE
Não é possível instalar pelo Composer

### ISSUE THREAD

**Issue by jcserracampos** [pagseguro/magento2#15]
Ao executar `composer require pagseguro/magento2`

Retorna

```
[InvalidArgumentException]                                                                                                                          
  Could not find package pagseguro/magento2 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by marcioshimoda** [comment]
@jcserracampos ... altere o "minimum-stability" do composer.json do Magento para "dev"

**Comment by jcserracampos** [comment]
@marcioshimoda Eu tentei instalar pelo packagist

**Comment by marcioshimoda** [comment]
@jcserracampos ... localize o arquivo composer.json que fica na raiz do Magento, procure a linha que define o minimum-stability e troque para dev... depois execute novamente o composer require pagseguro/magento2

**Comment by gabriellucius** [comment]
Boa tarde @jcserracampos !

Os procedimentos citados pelo @marcioshimoda  estão corretos e devem resolver seu problema.

Esse problema ocorria devido ao fato de não haver uma _tag_ estável ainda para o módulo, mas a mesma já foi criada e agora o comando `composer require pagseguro/magento2` deve funcionar normalmente.
**Observação:** pode ser necessário utilizar previamente o comando `composer clear-cache`, para limpar o cache do composer antes de executar o `composer require`.

Se puder, por favor, teste novamente e retorne o resultado para que possamos fechar essa issue.
E obrigado pela contribuição! :D

**Comment by gabriellucius** [comment]
Estou fechando a issue, caso ocorra novamente poderá ser reaberta.

**Comment by FabioYeff** [comment]
Bom dia pessoal, eu tenho em meu servidor o php 7.1.4 preciso alterar para instalar o pagseguro???  Já alterei o minimum stabilty do composer.json para dev ... limpei o cache do composer ... e mesmo assim deu erro na instalação:
[InvalidArgumentException]
  Could not find package pagseguro/magento2 at any version matching your PHP version 7.1.4.0

Alguém tem ideia do que eu posso fazer para instalar?

**Comment by dalvan03** [comment]
Também estou tendo este erro

Package pagseguro/magento2 at version  has a PHP requirement incompatible with your PHP version (7.1.30)
