### ISSUE TITLE
library file

### ISSUE THREAD

**Issue by alex5896ml** [pagseguro/magento2#16]
I have checked Pagseguro and the issue is from extension which does not include Library

Class 'PagSeguro\Library' not found in /home/27000-72579.cloudwaysapps.com/urxaxeaaqs/public_html/app/code/UOL/PagSeguro/Helper/Library.php on line 105

**Comment by lcsbaroni** [comment]
I opened a PR to fix this. https://github.com/pagseguro/magento2/pull/17
