### ISSUE TITLE
Uncaught TypeError: Cannot read property 'installments' of undefined

### ISSUE THREAD

**Issue by gsc-dev** [pagseguro/magento2#24]
Este erro aparece assim que adiciono o numero do cartao no formulario de pagamento.

A ampulheta do magento aparece e nao consigo concluir o pagamento.

![image](https://cloud.githubusercontent.com/assets/18435451/22403940/db3a12b4-e61d-11e6-9219-509dc02ecf67.png)

![image](https://cloud.githubusercontent.com/assets/18435451/22403946/06040dec-e61e-11e6-8297-b63969927c28.png)

**Comment by gsc-dev** [comment]
Parece que o problema e vem do algoritmo que faz o logging

![image](https://cloud.githubusercontent.com/assets/18435451/22404038/012b89e2-e620-11e6-934a-40c82506821f.png)

**Comment by gsc-dev** [comment]
Colocando um nome de arquivo na configuracao de log resolve o problema, mas descricao na configuracao poderia estar mais claro que e preciso o path para um arquivo e nao um diretorio

Tambem, o tratamento do erro no formulario de pagamentos poderia ser melhor.

![image](https://cloud.githubusercontent.com/assets/18435451/22404148/e7ff2980-e622-11e6-91df-1687ad918835.png)

**Comment by gabriellucius** [comment]
Boa tarde @gsc-dev !

Já alteramos a descrição e as mensagens referente à configuração do log (vide imagem abaixo), em breve vamos subir para versão estável essas alterações.

![new-log](https://cloud.githubusercontent.com/assets/8374748/22564418/99658c46-e96b-11e6-85ea-d99ecc3f83a5.png)


Obrigado pela colaboração (:

**Comment by gsc-dev** [comment]
Ola @gabriellucius ,

As mudancas ja estao disponiveis?

Tentei autalizar via composer mas nao veio nada novo.

Obrigado,
Ronaldo
