### ISSUE TITLE
credit card holder area code is required

### ISSUE THREAD

**Issue by gsc-dev** [pagseguro/magento2#25]
O plugin requer o campo "sender.areaCode"

Como faco para habilitar?

**Comment by gabriellucius** [comment]
Olá @gsc-dev!

Não é algo que seja habilitado no módulo, essa mensagem é o retorno do PagSeguro quando o DDD não está sendo passado junto com o número do telefone do cliente.

Verifique se no cadastro de usuário (comprador) está sendo inserido um telefone com DDD.

**Comment by gsc-dev** [comment]
Ola @gabriellucius ,

O telefone no Magento 2 e um campo livre sem formatacao ou mascara alguma.

Acredito que muitos usuarios irao digitar o telefone no formato errado e nao conseguirao finalizar o checkout.

Nao ha como o modulo adicionar uma validacao ou uma mascara no formulario de checkout?

Obrigado,
Ronaldo

**Comment by gabriellucius** [comment]
Então, é complicado para o módulo alterar o formulário de cadastro do Magento, pode causar conflito com temas ou customizações específicas das lojas.

O que poderia ser pensado era talvez adicionar na tela do checkout transparente um campo para digitar o telefone, onde poderíamos validar e aplicar máscaras, mas por outro lado estaríamos fazendo com o que o usuário da loja fornecesse o telefone em dois momentos distintos (cadastro e pagamento).

**Comment by gsc-dev** [comment]
Oi @gabriellucius,

Se nao houver como modificar a api para nao rejeitar a compra, acho que ainda assim, vale a pena.

Pelo meu ponto de vista, prefiro que ter uma incompatibiliade com outros plugins  (que eu sei que existe, e posso concertar ainda no ambiente de desenvolvimento), do que ter clientes no ambiente de producao que nao conseguem comprar (na pratica, so irei saber do problema apos ter uma reclamacao).

Teria com implementar a validacao e mascaras com uma configuracao no admin? Isso poderia resolver casos de incompatibilidade.

**Comment by gabriellucius** [comment]
O DDD é um requisito obrigatório para o sistema então a API não vai aceitar o mesmo não ser passado.

O módulo serve para realizar pagamentos utilizando o PagSeguro. Daria para alterar o formulário de cadastro de endereço para adicionar máscaras, mas o módulo fazendo isso estaria saindo do seu escopo, além de estar interferindo numa área que o usuário da loja pode querer customizar como quiser.

Na minha opinião, personalização de formulário de cadastro de endereço de cliente é responsabilidade da loja (via customização, tema) não de um módulo de pagamento. Enquanto isso, o  módulo aceita telefones com máscaras, parenteses, traços, espaços, desde que seja passado um DDD.
