### ISSUE TITLE
Folha de estilo com seletores muito abrangentes

### ISSUE THREAD

**Issue by pguedesbr** [pagseguro/magento2#28]
O arquivo style.css desse módulo possui uma série de seletores extremamente abrangentes, com button, table, input, select.... etc sem nenhuma limitação de escopo.

Como resultado, as lojas ficam com seus temas deformados pelas regras de estilo do módulo do pagseguro. Isso precisa ser corrigido o quanto antes!

**Comment by andersao** [comment]
👍

**Comment by gabriellucius** [comment]
Olá @pguedesbr 

Realmente, a abrangência está maior que a necessária. Vamos providenciar as alterações assim que possível.

Se você puder, por favor, mencionar exemplos de temas, telas e/ou disponibilizar alguma evidência (print), que você tenha nos ajudaria no processo de validação das alterações.

Obrigado pela contribuição! (:

**Comment by pguedesbr** [comment]
@gabriellucius As consequências mais visíveis em meu modulo em desenvolvimento foram em labels (fonte branca) e tabelas (com bordas). A partir dessas evidencias constatei que a folha de estilo do pagseguro estava muito abrangentes.

**Comment by gabriellucius** [comment]
@pguedesbr você usa algum tema específico na sua loja? Você customizou os estilos da sua loja? Pode disponibilizar algum print do comportamento? (embora haja alguns seletores mais abrangentes no módulo, nas lojas de testes que temos não está comprometendo o layout, então caso você disponibilize mais informações ficará mais fácil atuar no problema).

**Comment by pguedesbr** [comment]
@gabriellucius estamos usando o tema Porto E-Commerce mas na real, não é muito relevante. 

Exemplo abaixo, um seletor ".label" mudando a cor dos atributos na aba de Mais Informações do produto:
![image](https://cloud.githubusercontent.com/assets/9370105/23261812/d94654f2-f9b6-11e6-9945-ff58f5aa3641.png)

Reitero que não devem tratar caso a caso. O que vocês devem fazer é **prefixar  todas as regras css com seletores que as limitem apenas a blocos do próprio módulo do Pagseguro**. Ou mais, **evitem usar regras css de reset** como parte do módulo.

**Comment by victornsc** [comment]
O meu tema também ficou quebrado depois de instalar o módulo.

Exemplo:
![screen shot 2017-03-01 at 18 08 53](https://cloud.githubusercontent.com/assets/4347977/23481510/6c17da56-feaa-11e6-821c-f8c54a12beef.png)

Sem o módulo:
![screen shot 2017-03-01 at 18 09 04](https://cloud.githubusercontent.com/assets/4347977/23481577/ae097b36-feaa-11e6-83a6-386f99111c77.png)

**Comment by willfrombrazil** [comment]
Algum update nesse bug? [Esta folha do pagseguro](https://github.com/pagseguro/magento2/blob/master/view/frontend/web/css/styles.css) está alterando diversas sessões de qualquer tema, até Blank e Luma. Não podem amarrar esses ajustes dentro de uma classe css do módulo?

**Comment by esilvajr** [comment]
@willfrombrazil ainda estamos validando.

**Comment by yuriolive** [comment]
Estão sendo selecionados todos elementos **th** e **td**
![pagseguro2](https://user-images.githubusercontent.com/10088631/29225984-b6015bde-7ea6-11e7-9860-72e9f9ebe5b8.png)
E o box sizing...
![pagseguro3](https://user-images.githubusercontent.com/10088631/29225985-b6055324-7ea6-11e7-8b0e-11a857fd623f.png)
