### ISSUE TITLE
Não é possível avançar no checkout, botão pagseguro desabilitado

### ISSUE THREAD

**Issue by pguedesbr** [pagseguro/magento2#29]
Ao fazer checkout com produtos virtuais, que nao exigem frete/endereço de entrega, não é possível avançar pra finalizar o pedido pelo pagseguro.

Há 3 formas de pagamento: Pagseguro, Check/Money order e Paypal.

Ao escolher pagseguro, o botão encontra-se desabiltado. Note-se que no meio de pagamento do pagseguro, não há o campo para escolher/preencher o endereço.

Se você alterar a forma de pagamento pra dinheiro, que possui o campo pra escolher os dados de cobrança/endereço, você pode selecionar um endereço e clicar em "Atualizar". 

Uma vez definido o endereço de cobrança via check/money order, pode-se alternar novamente pro pagseguro e o botão pra finalizar o pedido estará habilitado.

**Comment by gabriellucius** [comment]
Oi @pguedesbr!

Obrigado pela informação, vamos validar o problema.

**Comment by glaucomorais** [comment]
Isso tem haver com um problema que estou tendo no momento: #75.

Seria necessário incluir o bloco que permite o cliente escolher o endereço de cobrança no próprio método de pagamento, pois a configuração contempla esse tipo de opção e por conta disso me vi forçado a fazer com que o Magento sempre exiba o endereço de cobrança na página de pagamentos (tanto por causa do PagSeguro, tanto por causa de um módulo do Itaú Shopline).

**Comment by ghost** [comment]
@glaucomorais  Foi lançado uma nova versão do plugin com correções pode verificar se foi corrigido o problema relatado !
