### ISSUE TITLE
Error:  Uncaught ReferenceError: WS is not defined

### ISSUE THREAD

**Issue by welitonfreitas** [pagseguro/magento2#30]
Ao clicar em concluir no checkout transparente está sendo exibido esse error:

Uncaught ReferenceError: WS is not defined
    at HTMLButtonElement.<anonymous> ((index):380)
    at HTMLButtonElement.dispatch (eval at require.load (4ece360….min.js:formatted:2008), <anonymous>:310:451)
    at HTMLButtonElement.elemData.handle (eval at require.load (4ece360….min.js:formatted:2008), <anonymous>:283:173)

O erro ocorrer para qualquer forma de pagamento do pagseguro.
Estou usando o magento 2.1.4

**Comment by gabriellucius** [comment]
Olá @welitonfreitas. Poderia informar qual versão do módulo do PagSeguro você está utilizando?

**Comment by welitonfreitas** [comment]
Olá @gabriellucius, a versão que está no meu composer e dev-master. Nem consigo debugar direito para tentar achar o error, acredito que esteja no iframe do chekout transparente.

**Comment by lcsbaroni** [comment]
Estou usando a versão 1.3.0 e tive o mesmo erro.
Ao abrir o checkout já da o seguinte erro:
`VM19147:2 Uncaught TypeError: element.prop is not a function`
Ao clicar em concluir:
`(index):1979 Uncaught ReferenceError: WS is not defined`

**Comment by ghost** [comment]
@lcsbaroni @welitonfreitas pode me informar se já conseguiu resolver seu problema com versão mais atuais ou continua com o mesmo problema relatado acima ?

**Comment by lcsbaroni** [comment]
@felipebranco na versão 1.12.0 esse problema não ocorre mais.

**Comment by lobobruno** [comment]
Continuo com o problema na versão 1.12.0.... quando abro no Admin -> PagSeguro -> Lista de Transaçoes da o erro:  Uncaught ReferenceError: WS is not defined.

"pagseguro/magento2": "1.12.0",
"pagseguro/pagseguro-php-sdk": "4.2.1",
"pagseguro/php": "^2.7"
