### ISSUE TITLE
Erro No Magento após instalar modulo PagSeguro

### ISSUE THREAD

**Issue by lffruhling** [pagseguro/magento2#32]
Boa tarde, percebi que após instalar o módulo do pagseguro, o magento começou a apresentar um erro no cadastramento de novos níveis de permissão.

Para identificar o erro, basta instalar o modulo do pagseguro no magento e acessar: System > User Roles > Add new Role > Role Resources > Selecionar Custom em Resources Access, logo abaixo deste campo, o campo Resources deveria listar uma grade com as áreas do magento.

**Comment by lffruhling** [comment]
Solução até o momento :

php bin/magento module:status
php bin/magento module:disable UOL_PagSeguro
php bin/magento setup:upgrade

Isto irá desativar o módulo do magento e voltará a funciona as permissões. após editar as permissões, habilite o módulo do maneto novamente

php bin/magento module:enable UOL_PagSeguro
php bin/magento setup:upgrade

**Comment by gabriellucius** [comment]
Olá @lffruhling, vamos validar esse comportamento e, caso seja um bug mesmo, iremos trabalhar na correção do mesmo e continuaremos com a comunicação por aqui.

Obrigado pela contribuição!
