### ISSUE TITLE
Formatação do formulário de pagamentos

### ISSUE THREAD

**Issue by gsc-dev** [pagseguro/magento2#33]
Ola,

O formato do formulario de pagamentos nao fica bom em meia tela ( 940 px )

![image](https://cloud.githubusercontent.com/assets/18435451/23101520/3ae4be38-f68d-11e6-8357-9f3201a075de.png)

**Comment by gabriellucius** [comment]
Olá @gsc-dev vamos validar a issue e trabalhar numa possível correção.

Obrigado pela contribuição! (:
