### ISSUE TITLE
sender name invalid value: Convidado

### ISSUE THREAD

**Issue by gsc-dev** [pagseguro/magento2#34]
Ola,

O modulo esta com problemas quando a compra e feita por um magento "guest" sem cadastro no site:

Erro: **<errors><error><code>53015</code><message>sender name invalid value: Convidado</message></error></errors>**

```
19/02/2017 07:21:10 PagSeguro.Checkout[info]: Params: {"reference":"4c619af19","billingAddress.street":"Rua Felipe Schmidt","billingAddress.number":"111","billingAddress.complement":"Centro","billingAddress.city":"Itaja\u00ed","billingAddress.state":"SC","billingAddress.district":"Rua Felipe Schmidt","billingAddress.postalCode":"88301041","billingAddress.country":"Brasil","currency":"BRL","creditCard.holder.name":"Jose da Silva","creditCard.holder.birthDate":"20\/01\/1980","creditCard.holder.areaCode":"47","creditCard.holder.phone":"99222099","creditCard.holder.CPF":"22222222222","installment.quantity":"1","installment.value":"111.00","item[1].id":"20","item[1].description":"L'Or\u00e9al Professionnel Condicionador Absolut Repair P\u00f3s-Qu\u00edmica Multi-reconstrutor - 150ml","item[1].quantity":1,"item[1].amount":"94.90","payment.method":"creditCard","sender.name":"Convidado","sender.email":"magento2@sandbox.pagseguro.com.br","sender.areaCode":"47","sender.phone":"99222099","sender.CPF":"22222222222","sender.hash":"a14ec9b995e5787f0d376ab211ecb437df2687d9f5708a5f137b799c6d78d96e","shipping.type":3,"shipping.cost":"16.10","shipping.address.street":"Rua Felipe Schmidt","shipping.address.number":"314","shipping.address.complement":"Centro","shipping.address.city":"Itaja\u00ed","shipping.address.state":"SC","shipping.address.district":"Rua Felipe Schmidt","shipping.address.postalCode":"88301041","shipping.address.country":"Brasil","creditCard.token":"1ec34378458444f6ab3ab8eda1db6328"}
19/02/2017 07:21:12 PagSeguro.DirectPayment.CreditCard[error]: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>sender name invalid value: Convidado</message></error></errors>
```

![image](https://cloud.githubusercontent.com/assets/18435451/23113091/825679f0-f72d-11e6-91ab-ace2e41011f8.png)

**Comment by gabriellucius** [comment]
Olá @gsc-dev , vamos validar essa issue e, confirmado o bug, iremos atuar na resolução do mesmo.

Obrigado pela contribuição!

**Comment by gcampedelli** [comment]
Sim, no checkout transparente tenho encontrado esse problema.  A outra coisa é a seguinte, o atendimento do PagSeguro é incapaz de informar com precisão se o checkout transparente está ou não habilitado para a conta. Acredito que o PagSeguro deva atualizar suas políticas para tornar o processo mais dinâmico.

**Comment by willfrombrazil** [comment]
Botão "Finalizar Pedido" fica desabilitado quando usuário não tem conta cadastrada no Magento (guest).

Vídeo mostrando que só é possível continuar quando se cadastra um endereço através da opção pagamento em dinheiro do Magento: https://youtu.be/BRVhDqPvTOw

Checkout Transparente
Sandbox mode
Magento ver. 2.1.3
Chrome Version 56.0.2924.87 Mac OS 10.10.5 e Android 6.0

**Comment by gabriellucius** [comment]
@gsc-dev implementamos a correção na branch de desenvolvimento, consegue validar se resolveu seu problema?
Esse é o link do PR: https://github.com/pagseguro/magento2/pull/55/files

**Comment by gsc-dev** [comment]
Ola @gabriellucius ,

Fiz o update do modulo via composer e o problema ainda persiste

<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>**sender name invalid value: Convidado**</message></error></errors>


Quando há um erro, o modulo falha sem nenhuma orientação ao usuario, que certamente irá desistir da compra.

![image](https://cloud.githubusercontent.com/assets/18435451/25508811/8639c5e6-2bac-11e7-9558-10ea50400e05.png)

Isto acontece quando:
 - o cliente faz a compra como convidado
 - o cliente nao inclui o DDD no telefone (favor, adicione um DDD default qualquer, pois e melhor nao ter o DDD do que perder o cliente)
 -  o cliente insere qualquer outro error no formulario 

Voce poderia acrecentar uma mensagem para orientar o cliente qual foi o motivo do erro?


Além disso, o formulário de pagamentos ainda não fica certo na tela, ( o que fara um grande numero de clientes desistir da compra por achar o site nao confiavel)

![image](https://cloud.githubusercontent.com/assets/18435451/25508640/6a3d6c68-2bab-11e7-8880-d29385c88f49.png)

**Comment by gcampedelli** [comment]
Olá, tente o seguinte método

Edite o seu arquivo rules.js localizado do module-ui e copei para a pasta app/design/frontend/seutema/seutema/Magento_Ui/web/js/lib/validation

Edite e adicione a seguinte linha depois de phoneUK

"phoneBR": [
            function(value) {
                value = value.replace(/\s+/g, "");
                return value.length > 11 && value.match (/^(0[1-2][1-9]9\d{8})|(0[3-9][1-9]\d{8})$/);
            },
            $.mage.__('Coloque um celular no formato (0xx) xxxx-xxxx')
        ],

Copiei seu checkout_index_index.xml para a pasta equivalente do seu tema e adicione o código

       
      *** <item name="shipping-address-fieldset" xsi:type="array">
                <item name="children" xsi:type="array">
                           <item name="telephone" xsi:type="array">
                            <item name="config" xsi:type="array">
                                    <item name="tooltip" xsi:type="array">
                                           <item name="description" xsi:type="string" translate="true">Texto.</item>
                                      </item>
                             </item>
  
                        <item name="validation" xsi:type="array">
                                  <item name="phoneBR" xsi:type="string">true</item>
                         </item>
                   </item>
           </item>
  </item>***


Delete var/cache
            var/page-cache
            var/generation
            var/view-preprocessed
            var:di
            pub/static/frontend (mantenha o .htaccess)

php bin/magento cache:disable
                              setup:upgrade
                              setup:di:compile
                               setup:static-content:deploy
                               cache:flush
                               cache:enable

O Regex pede para colocar o 0 na frente do DDD. Caso você queira, pode descobrir um Regex mais adequado para seus propósitos. 

Boa sorte
Até mais
Gabriela

**Comment by gabriellucius** [comment]
@willfrombrazil abra uma outra issue pro problema relatado, por favor

**Comment by gabriellucius** [comment]
@gsc-dev vamos precisar debugar melhor o que está acontecendo no seu caso na compra como convidado, pois a implementação estava com problema antes mesmo, mas agora está ok. Me parece alguma inconsistência relacionada à tradução. 
Preciso saber o que está retornando nas chamadas ```(string)__('Guest')``` e ```$this->_order->getCustomerName()``` nas chamadas dentro dos models do checkout transparente do PagSeguro *(minha-loja-magento2/vendor/pagseguro/magento2/Model/Direct/BoletoMethod.php, por exemplo)*

Quanto à questão do DDD, é uma regra da documentação da API do PagSeguro que ele seja passado obrigatoriamente então não podemos simplesmente fixar um valor aleatório. 

E a questão do layout já entrou no nosso backlog.

**Comment by gabriellucius** [comment]
Implementamos mais uma melhoria na validação da compra como convidado no PR https://github.com/pagseguro/magento2/pull/58

**Comment by donatoaz** [comment]
Este issue ainda está aberto? Estou recebendo o mesmo erro ao tentar fazer o checkout no sandbox.

> 09/09/2017 09:54:19 PagSeguro.DirectPayment.CreditCard[error]: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>sender name invalid value: Guest</message></error></errors>

```
09/09/2017 09:53:31 PagSeguro.Installment[info]: Begin
09/09/2017 09:53:31 PagSeguro.Installment[info]: GET: https://ws.sandbox.pagseguro.uol.com.br/v2/installments?email=***%40***.com&token=***&amount=30.00&cardBrand=visa
09/09/2017 09:54:18 PagSeguro.DirectPayment.CreditCard[info]: Begin
09/09/2017 09:54:18 PagSeguro.DirectPayment.CreditCard[info]: POST: https://ws.sandbox.pagseguro.uol.com.br/v2/transactions/?email=***%40***.com&token=***
09/09/2017 09:54:18 PagSeguro.Checkout[info]: Params: {"reference":"10352856","billingAddressStreet":"r. Concei\u00e7\u00e3o do Mato Dentro","billingAddressNumber":"240","billingAddressComplement":"","billingAddressCity":"Belo Horizonte","billingAddressState":"MG","billingAddressDistrict":"r. Concei\u00e7\u00e3o do Mato Dentro","billingAddressPostalCode":"31310240","billingAddressCountry":"Brasil","currency":"BRL","creditCardHolderName":"TESTE TESTE","creditCardHolderBirthDate":"19\/01\/1986","creditCardHolderAreaCode":"31","creditCardHolderPhone":"33119000","creditCardHolderCPF":"10854831185","installmentQuantity":"1","installmentValue":"30.00","itemId1":"6","itemDescription1":"Produto Teste","itemQuantity1":1,"itemAmount1":"25.00","itemWeight1":1,"paymentMethod":"creditCard","senderName":"Guest","senderEmail":"magento2@sandbox.pagseguro.com.br","senderAreaCode":"31","senderPhone":"(**) 3311-****","senderCPF":"108.***.***-**","senderHash":"e8f7d59a45925abc2b442866555357bbf70a09714f45b6c4dc948ce1eb2232ec","shippingType":3,"shippingCost":"5.00","shippingAddressStreet":"r. Concei\u00e7\u00e3o do Mato Dentro","shippingAddressNumber":"240","shippingAddressComplement":"","shippingAddressCity":"Belo Horizonte","shippingAddressState":"MG","shippingAddressDistrict":"r. Concei\u00e7\u00e3o do Mato Dentro","shippingAddressPostalCode":"31310240","shippingAddressCountry":"Brasil","creditCardToken":"6b810762810a40c495fff644384bb63e"}
09/09/2017 09:54:19 PagSeguro.DirectPayment.CreditCard[error]: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>53015</code><message>sender name invalid value: Guest</message></error></errors>
```

**Comment by lcsbaroni** [comment]
@gabriellucius quando esse PR (https://github.com/pagseguro/magento2/pull/55/files) vai entrar para a versão estável?

Sem isso, o checkout transparente não funciona.
Obrigado

**Comment by lcsbaroni** [comment]
@gabriellucius alguma novidade? Sem isso toda vez que faço deploy tenho que corrigir esses arquivos.

**Comment by ghost** [comment]
@lcsbaroni Foi lançada uma nova versão do plugin do Pagseguro do Módulo, pode verificar se foi corrigido seu problema, caso não me comunique por aqui novamente.
