### ISSUE TITLE
Não é possível realizar checkout como Guest

### ISSUE THREAD

**Issue by willfrombrazil** [pagseguro/magento2#35]
Botão "Finalizar Pedido" fica desabilitado quando usuário  não tem conta cadastrada no Magento (guest).

[Vídeo mostrando](https://youtu.be/BRVhDqPvTOw) que só é possível continuar quando se cadastra um endereço através da opção pagamento em dinheiro do Magento:

https://youtu.be/BRVhDqPvTOw

Checkout Transparente
Sandbox mode
Magento ver. 2.1.3
Chrome Version 56.0.2924.87 Mac OS 10.10.5 e Android 6.0

**Comment by gcampedelli** [comment]
Olá, não sei se estou enfrentando o mesmo problema e se minha configuração na API do PAG Seguro está correta, mas tentei seguir as instruções e não achei claro o suficiente. 

Instalei o Pag Seguro usando o composer no meu site Magento 2.0.0. Estou usando as configurações do Sandbox. Alguma solução. Tem que mexer no .htaccess? A propósito, não consegui realizar o chek-out nem se eu criar a conta de consumidor. 

O módulo está perfeitamente instalado, mas eu recebo erro 500 no servidor no método POST checkout com Ligthbox

POST https://...../rest/english/V1/guest-carts/...../payment-information 500 (Internal Server Error)

send	@	jquery.js:9666
ajax	@	jquery.js:9211
post	@	storage.js:39
(anonymous)	@	place-order.js:17
(anonymous)	@	place-order.js:33
_super	@	wrapper.js:73
(anonymous)	@	place-order-mixin.js:20
(anonymous)	@	wrapper.js:78
(anonymous)	@	payment-method.js:64
fire	@	jquery.js:3099
fireWith	@	jquery.js:3211
done	@	jquery.js:9310
callback	@	jquery.js:9720

**Comment by gabriellucius** [comment]
Acredito que esteja relacionada a issue #34

**Comment by gcampedelli** [comment]
Olá gabriellucius, obrigada pela resposta. No meu caso, percebi que faltavam algumas dependências. Instalei o DOM e tudo voltou a funcionar.   
Não cheguei a concluir completamente o flow de pagamento porque ainda estou usando um servidor sem o domínio, mas fui até a abertura do lightbox do Pag Seguro. 
Se aparecerem outros problemas volto a esse fórum. 
Obrigada pela atenção. 
Gabriela

**Comment by gcampedelli** [comment]
Olá gabriellucius, embora o Lightbox tenha aberto, no checkout transparente, a minha página de retorno é pagseguro/payment/failure/ 

Eu ainda não transferi o DNS para o meu domínio e nõa fiz testes em Sandbox. Na verdade, eu notei algumas mudanças na API de pagamentos e gostaria de ter uma explicação melhor de como usá-las, tipo um tutorial. 
A outra questão é a seguinte. Imagino que o Pagseguro poderia ter um Oauth que, quando o consumidor escolhe esse login para cadastro no site do Magento, insere a senha do Pagseguro e voilá. Isso facilitaria a vida de todo mundo, tanto da loja, quanto a do PagSeguro e, tenho certeza, de que aumentaria as vendas, menos carrinhos seriam abandonados etc. Tipo compra com um ou dois cliques. 
Eu imagino que a API de Pagamentos permita fazer esse workaround, mas ainda tenho algumas dúvidas de como usar suas funcionalidades e não encontro resposta para elas. Existe algum tutorial para nos indicar? 

Obrigada
Gabriela
