### ISSUE TITLE
Máscara CPF altera ordem dos caracteres digitados

### ISSUE THREAD

**Issue by willfrombrazil** [pagseguro/magento2#36]
Máscara do formato CPF trava cursor após cada ponto adicionado.

[Vídeo mostrando](https://youtu.be/YdASoN6AvE8) um exemplo onde digito 0123456789 e o campo é preenchido com 012.987.654-3 e, para funcionar, é necessário reposicionando o cursor após cada ponto adicionado pela máscara.

https://youtu.be/YdASoN6AvE8

Checkout Transparente
Sandbox mode
Magento ver. 2.1.3
Chrome Version 56.0.2924.87 Mac OS 10.10.5 e Android 6.0

**Comment by gabriellucius** [comment]
Olá @willfrombrazil qual versão do módulo você está utilizando?

Já temos ciência de um problema semelhante à esse e já corrigimos na branch de **desenvolvimento**, em breve vamos subir para master.

Você conseguiria testar com a versão que está na branch de desenvolvimento? (```composer require pagseguro/magento2:dev-desenvolvimento```)

**Comment by s2it-moscou** [comment]
Já disponibilizamos uma correção para esse problema na última versão do módulo. Vamos fechar a issue por falta de informações. Caso o erro ainda ocorra, reabriremos.
