### ISSUE TITLE
Problema com addressData['state']

### ISSUE THREAD

**Issue by rorteg** [pagseguro/magento2#37]
Na versão atual, estamos com problemas para fechar pedidos devido o módulo estar enviando para o Pagseguro $shipping['region'] aqui: https://github.com/pagseguro/magento2/blob/master/Model/PaymentMethod.php#L163

No caso de nosso projeto, está sendo enviado Paraná ao invés de PR e o Pagseguro nos retorna:"shippingAddressState invalid value: Paran�, must fit the pattern: \w{2} (e. g. "SP")"

Pois este valor pode variar de instalação para instalação do Magento. O correto nesse caso seria utilizar o campo $shipping['region_code'].

Estarei enviando uma PR em seguida, pois com estas alterações estou conseguindo fechar pedidos com sucesso.

Abraços

**Comment by gabriellucius** [comment]
Olá @rorteg.
O pull request não deve ser feito na branch master e sim na branch de desenvolvimento, onde iremos validar a alteração e aí fazer o pull para master.

Obrigado pela contribuição! (:

**Comment by gabriellucius** [comment]
Já implementamos essa correção, inclusive a incrementamos na branch master no PR https://github.com/pagseguro/magento2/pull/58

**Comment by s2it-moscou** [comment]
Melhoria aplicada, caso o comportamento persista abriremos novamente a issue.
