### ISSUE TITLE
Erro ao listar transações para conciliação (Uncaught TypeError)

### ISSUE THREAD

**Issue by victornsc** [pagseguro/magento2#42]
Instalei o módulo recentemente (versão 1.2.0) e estou tendo problemas para conciliar transações. Ao clicar no botão de pesquisar, ele não retorna as transações. O mesmo problema também ocorre com transações abandonadas, cancelamento e estorno.

O PHP gera o seguinte log:

Conciliação:
> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to UOL\PagSeguro\Model\Transactions\Methods\Conciliation::__construct() must be an instance of Magento\Framework\Model\ResourceModel\Db\Context, instance of Magento\Framework\App\ResourceConnection given, called in /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Conciliation/Request.php on line 65 and defined in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Conciliation.php:95
Stack trace:
#0 /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Conciliation/Request.php(65): UOL\PagSeguro\Model\Transactions\Methods\Conciliation->__construct(Object(Magento\Framework\App\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Framework\Model\ResourceModel\Db\Context), Object(Magento\Backend\Model\Session\Interceptor), Object(Magento\Sales\Model\Order), Object(UOL\PagSeguro\Helper\Library), Object(UOL\PagSeguro\Helper\Crypt), '5')
#1 /var/www/magento2/var/generation/UOL/PagSeguro/Controller/Adminhtml/Conc in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Conciliation.php on line 95

Abandonadas:

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to UOL\PagSeguro\Model\Transactions\Methods\Abandoned::__construct() must be an instance of Magento\Framework\Mail\Template\TransportBuilder, instance of Magento\Framework\App\ResourceConnection given, called in /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Abandoned/Request.php on line 63 and defined in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Abandoned.php:102
Stack trace:
#0 /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Abandoned/Request.php(63): UOL\PagSeguro\Model\Transactions\Methods\Abandoned->__construct(Object(Magento\Framework\App\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Framework\Mail\Template\TransportBuilder), Object(Magento\Framework\Model\ResourceModel\Db\Context), Object(Magento\Backend\Model\Session\Interceptor), Object(Magento\Sales\Model\Order), Object(UOL\PagSeguro\Helper\Library), Object(UOL\PagSeguro\Helper\Crypt), Object(Magento\Framework\Stdlib\Date in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Abandoned.php on line 102

Cancelamento:

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to UOL\PagSeguro\Model\Transactions\Methods\Cancellation::__construct() must be an instance of Magento\Framework\Model\ResourceModel\Db\Context, instance of Magento\Framework\App\ResourceConnection given, called in /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Cancellation/Request.php on line 62 and defined in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Cancellation.php:90
Stack trace:
#0 /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Cancellation/Request.php(62): UOL\PagSeguro\Model\Transactions\Methods\Cancellation->__construct(Object(Magento\Framework\App\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Framework\Model\ResourceModel\Db\Context), Object(Magento\Backend\Model\Session\Interceptor), Object(Magento\Sales\Model\Order), Object(UOL\PagSeguro\Helper\Library), Object(UOL\PagSeguro\Helper\Crypt), '5')
#1 /var/www/magento2/var/generation/UOL/PagSeguro/Controller/Adminhtml/Canc in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Cancellation.php on line 90

Estorno:

> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to UOL\PagSeguro\Model\Transactions\Methods\Refund::__construct() must be an instance of Magento\Framework\Model\ResourceModel\Db\Context, instance of Magento\Framework\App\ResourceConnection given, called in /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Refund/Request.php on line 60 and defined in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Refund.php:90
Stack trace:
#0 /var/www/magento2/vendor/pagseguro/magento2/Controller/Adminhtml/Refund/Request.php(60): UOL\PagSeguro\Model\Transactions\Methods\Refund->__construct(Object(Magento\Framework\App\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Framework\Model\ResourceModel\Db\Context), Object(Magento\Backend\Model\Session\Interceptor), Object(Magento\Sales\Model\Order), Object(UOL\PagSeguro\Helper\Library), Object(UOL\PagSeguro\Helper\Crypt), '5')
#1 /var/www/magento2/var/generation/UOL/PagSeguro/Controller/Adminhtml/Refund/Request/Interceptor.php(24) in /var/www/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Refund.php on line 90

**Comment by vlfreitas** [comment]
@victornsc já foi encontrado o problema. A correção será feita e disponibilizada.
