### ISSUE TITLE
Problema ao finalizar compra - erro 500

### ISSUE THREAD

**Issue by heldernm** [pagseguro/magento2#43]
Estou tendo problema ao finalizar o pagamento na seguinte URL {{dominio}}/rest/default/V1/carts/mine/payment-information, dá erro 500, mas quando abro a URL, consigo verificar o arquivo XML com as informações a ser enviada. Aparenta ser latência (É como o app buscasse o xml antes de ser gerado), mas não consigo ver. Não dá erro no apache, e nem vejo o erro no log do magento e não sei onde fica o log do pagseguro. Alguma solução? Uso o magento 2.0.13

**Comment by gabriellucius** [comment]
Oi @heldernm !

O log do PagSeguro é configurado através da interface administrativa do Magento. Recomendo apontar para um diretório com permissão de escrita e leitura (costumamos usar ```var/log/paseguro.log```)

Além de habilitar o log e checar onde está configurado para o mesmo ser gerado, outros pontos que seriam interessantes você nos passar:
- Qual tipo de Pagamento você está utilizando quando o erro ocorre? (Padrão, Lightbox ou Transparente)
- Qual versão do módulo você está utilizando? (pode usar o seguinte comando para verificar: ```composer show pagseguro/magento2``` )

**Comment by s2it-moscou** [comment]
Vamos fechar a issue por falta de informações. Caso erro persista, reabriremos a issue.
