### ISSUE TITLE
Pagseguro não inclui o valor de TAX

### ISSUE THREAD

**Issue by otaviogomes** [pagseguro/magento2#44]
Configurei uma regra de TAX dentro do Magento. A regra está sendo aplicada normalmente, conforme evidências nas telas de checkout e e-mails de confirmação, porém ao iniciar o pagamento no Pagseguro ele ignora o valor do TAX.

Estou usando o Pagseguro Sandbox.

**Comment by ghost** [comment]
@otaviogomes Desculpe a demora na resposta, seu problema foi solucionado, foi lançado uma noversão do plugin do Pagseguro para o Módulo, verifiquei se foi corrigido seu problema.
