### ISSUE TITLE
Pagseguro não aceita formato de telefone permitido pelo Magento

### ISSUE THREAD

**Issue by willfrombrazil** [pagseguro/magento2#45]
Recebo esse erro quando passo telefone cadastro numa conta do Magento 2. Se foi aceito pelo Magento, deveria ser aceito ou tratado pelo plugin do PagSeguro.

`1 exception(s):
Exception #0 (Exception): <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>11014</code><message>senderPhone invalid value: 2132358500</message></error></errors>`

**Comment by gabriellucius** [comment]
Oi @willfrombrazil. 
Eu tentei reproduzir seu erro aqui, mas não consegui. Eu cadastrei um usuário com o telefone da sua mensagem de erro e o fluxo  de compra ocorreu normalmente.

Então, vou precisar de mais alguma informações:
- Como está salvo o número do telefone no endereço do usuário? (está adicionando +55 antes do telefone?)
- Qual versão do Magento 2 você está utilizando?
- Qual forma de checkout (padrão, lightbox ou transparente) você está utilizando?

**Comment by gabriellucius** [comment]
Adicionamos mais uma validação no número do telefone para os casos em que é passado o código do país também na branch master no https://github.com/pagseguro/magento2/pull/58

**Comment by s2it-moscou** [comment]
Foram aplicadas melhorias que podem corrigir o erro. Por falta de mais informações não temos como replicar com precisão. Teste novamente com a nova versão sugerida pelo @gabriellucius e caso o comportamento persista abriremos novamente a issue.
