### ISSUE TITLE
Aceita magento 2.1.5

### ISSUE THREAD

**Issue by isanat** [pagseguro/magento2#46]
Estou com a versão 2.1.5 sabe me dizer se esta ok nesta versão?

**Comment by isanat** [comment]
pelo visto não! não conclui o botao fica inativo.

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

**Comment by gabriellucius** [comment]
Olá @isanat 
Acho que nesse caso não é problema da versão do Magento. Eu tenho uma loja aqui com 2.1.5 e fiz os 3 tipos de checkout normalmente.

Preciso validar se o problema é o da issue referenciada acima.

**Comment by gabriellucius** [comment]
Vamos fechar a issue por falta de evidências. Caso o problema ainda ocorra, a mesma poderá ser reaberta.
