### ISSUE TITLE
Checkout Lightbox - Error PHP não identificado

### ISSUE THREAD

**Issue by willfrombrazil** [pagseguro/magento2#47]
Módulo permite que usuário informe um url inexistente para criação de log e acaba escrevendo mensagem de erro no frontend, como nesta simulação  https://youtu.be/j48g7r-RNWE

Sugestão: fixar o diretório de log padrão do Magento /var/log

**Comment by gabriellucius** [comment]
@willfrombrazil  Adicionamos o caminho padrão do log na branch master no PR https://github.com/pagseguro/magento2/pull/58

Obrigado pela contribuição!

**Comment by s2it-moscou** [comment]
Melhoria aplicada, caso o comportamento persista abriremos novamente a issue.
