### ISSUE TITLE
Botão "Finalizar" não funciona quando Pagseguro é o único método de pagamento

### ISSUE THREAD

**Issue by LeartPinheiro** [pagseguro/magento2#48]
Olá! Estou tentando usar o modulo Pagseguro como único meio de pagamento, porém o botão "Finalizar", na seleção de pagamento não funciona. Você clica, aparece a rodinha no meio da tela de carregamento e depois para e o botão fica inativo. 
 *Isso só ocorre se o Pagseguro for a unica forma de pagamento (talvez tenha algo a vê com a bolinha de seleção que só aparece quando há mais de um meio de pagamento).
*Testei em varias versões do Magento, atualmente estou tentando na 2.1.5.
*Tentei na versão 1.2.0  e na versão do branch developers do modulo.

**Comment by luizpcam** [comment]
Acontece a mesma coisa comigo, mas dei uma olhada no log é cheguei a esse request:
```
https://ws.sandbox.pagseguro.uol.com.br/v2/installments?email=luizpca
m%40gmail.com&token=FB0035F7A62543319967EDEA41C5B07A&amount=559.90&cardBrand=    1
```

Aparentemente o cardBrand esta errado e isso faz com que o retorno chegue errado:
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<errors>
    <error>
        <code>54007</code>
        <message>invalid brand:    1</message>
    </error>
</errors>
```

**Comment by gcampedelli** [comment]
Caros desenvolvedores do Pag Seguro. O módulo funciona, é ótimo, porém algumas coisas podem ser melhoradas, como por exemplo a desse tópico
Acontece a mesma coisa comigo quando eu deixo só o PagSeguro habilitado.Todos os outros meios de pagamento funcionam quando estão somente eles habilitados, somente o PagSeguro que não inicia
Eu quis me aventurar a mudar o código para que funcione, mas ainda não testei e tenho medo de testar. 
Pelo que eu entendi, o módulo teria que estender o defaul.js do Magento\Checkout\view\frontend\web\js\view\payment\default.js

define(
['Magento_Checkout/js/view/payment/default'],

 function(Component) {
    initObservable: function () {
        this._super();
        this.selectPaymentMethod();
        ...
    }
});
E se tivar iniciação demorada usar o onReady event

Peço que os desenvolvedores resolvam isso rapidamente

Obrigada, 
Gabriela

**Comment by victornsc** [comment]
Enquanto o problema não é corrigido você pode tentar essa solução aqui:
https://github.com/pagseguro/magento2/issues/12#issuecomment-293302931

**Comment by gcampedelli** [comment]
Funcionou. Obrigada!
