### ISSUE TITLE
Não dá para sair da tela Lightbox após gerar boleto (Mobile / Android) + pdf corrompido

### ISSUE THREAD

**Issue by otaviogomes** [pagseguro/magento2#49]
Problema encontrado utilizando celular Android 4.4.2, navegador Chrome.

Após efetuar o procedimento de pagamento com boleto não dá para sair da tela de pagamento e retornar ao site original. No navegador desktop dá para fechar a janela do lightbox, mas no mobile não dá (imagem em anexo).
![screenshot_2017-03-27-14-17-35](https://cloud.githubusercontent.com/assets/13907086/24369189/8e3a19ce-12f9-11e7-8dbe-81eb08e2dab4.png)

Além disso, o arquivo .pdf do boleto parece estar corrompido.

**Comment by vlfreitas** [comment]
@otaviogomes tudo bem? O Pagseguro não dá suporte responsivo ao Lightbox. Você pode até conseguir realizar as compras, porém podem ocorrer alguns imprevistos como esses de fechar ou retornar ao site original. Obrigado
