### ISSUE TITLE
Falha ao fazer pagamento com checkout transparente

### ISSUE THREAD

**Issue by bruno-rodrigues** [pagseguro/magento2#5]
**Problema**

A requisição enviada ao servidor PagSeguro falhar porque o formulário de checkout do Magento não possui alguns campos que são obrigatórios:

```
<?xml version="1.0" encoding="UTF-8"?>
    <errors>
        <error>
            <code>53018</code>
            <message>sender area code is required.</message>
        </error>
       <error>
      <code>53015</code>
      <message>sender name invalid value: Guest</message>
   </error>
   <error>
      <code>53026</code>
      <message>shipping address number is required.</message>
   </error>
   <error>
      <code>53034</code>
      <message>shipping address state invalid value: Goiás</message>
   </error>
</errors>
```

**Solução** 
Adicionar esses campos no form de checkout, preenchendo  `shipping address` e `billing address` com valores válidos antes de enviar a requisição para o PagSeguro.

Estou trabalhando nessa possível solução e caso tudo funcione envio um Pull request.

**Comment by caioiglesias** [comment]
Que versão você usou Bruno?

**Comment by glaucomorais** [comment]
A UX tá bem ruim com o checkout transparente.
Creio que seria bom os campos de telefone aparecerem para serem conferidos antes de enviar o pedido.
Porque a compra é considerada falha por conta de dados de cadastro que poderiam ser revistos antes de realizar o pedido.

**Comment by gcampedelli** [comment]
Surgiu alguma solução para isso?

**Comment by ghost** [comment]
@glaucomorais @gcampedelli Foi lançado uma nova versão á 14 dias verifiquei se foi solucionado o problema e qualquer dúvida mande mensagem novamente.
