### ISSUE TITLE
Erro ao compilar na versão 2.1.5

### ISSUE THREAD

**Issue by rafaelrocha007** [pagseguro/magento2#50]
Bom dia, estou com o seguinte erro executar ao setup:di:compile ou tentar setar o modo para produção:

`PHP Fatal error:  Cannot use PagSeguro\Domains\Requests\Payment as Payment because the name is already in use in \vendor\pagseguro\magento2\Model\PaymentMethod.php on line 26`

Alguem com o mesmo problema, ou conseguem me auxiliar?

**Comment by rafaelrocha007** [comment]
Resolvi mudando a linha 26 do Model\PaymentMethod.php para 
`use PagSeguro\Domains\Requests\Payment as UOLPayment;`

**Comment by luizpcam** [comment]
acontece a mesma coisa aqui ... vou tentar alterar para ver se funciona

**Comment by gabriellucius** [comment]
@rafaelcostarocha realmente o erro está ocorrendo. Providenciaremos a correção em breve, obrigado pela contribuição! :D

**Comment by gabriellucius** [comment]
@rafaelcostarocha  @luizpcam  Correção implementada na branch master no PR https://github.com/pagseguro/magento2/pull/58

**Comment by s2it-moscou** [comment]
Correção aplicada, caso o comportamento persista, abriremos novamente a issue.
