### ISSUE TITLE
Alterações Banco de dados

### ISSUE THREAD

**Issue by henriqueneves** [pagseguro/magento2#53]
1) Na tabela enderecos_clientes:
Alterar coluna 'numero' para varchar(10)
`ALTER TABLE `enderecos_clientes` CHANGE `numero` `numero` VARCHAR(255) NULL DEFAULT NULL; `

2) Na tabela enderecos_clientes:
Inserir coluna complemento

`ALTER TABLE `enderecos_clientes` ADD `complemento` VARCHAR(255) NOT NULL AFTER `numero`; `

**Comment by ghost** [comment]
@henriqueneves Sua sugestão foi repassada á Equipe de Desenvolvimento para validação/correção caso necessário ! Obrigado!
