### ISSUE TITLE
Cannot use PagSeguro\Domains\Requests\Payment as Payment because the name is already in use

### ISSUE THREAD

**Issue by gsc-dev** [pagseguro/magento2#56]
Erro ao executar:

**magento setup:di:compile**

Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 42.0 MiBPHP Fatal error:  Cannot use PagSeguro\Domains\Requests\Payment as Payment because the name is already in use in /srv/www/vendor/pagseguro/magento2/Model/PaymentMethod.php on line 26

Fatal error: Cannot use PagSeguro\Domains\Requests\Payment as Payment because the name is already in use in /srv/www/vendor/pagseguro/magento2/Model/PaymentMethod.php on line 26
Segmentation fault (core dumped)

**Comment by gabriellucius** [comment]
#50

**Comment by gabriellucius** [comment]
Olá @gsc-dev  já estamos trabalhando nessa correção (relatada na #50 )

**Comment by gabriellucius** [comment]
Correção implementada na branch master no PR https://github.com/pagseguro/magento2/pull/58

**Comment by s2it-moscou** [comment]
Correção aplicada, caso o comportamento persista, abriremos novamente a issue.
