### ISSUE TITLE
Modulo não criou pasta UOL_PagSeguro

### ISSUE THREAD

**Issue by nadinycostacurta** [pagseguro/magento2#6]
Estão ocorrendo erros de referenciação...estou utilizando o Magento 2.0.9.

Seguindo os passos da instalação, foram instaladas as devidas tables, as configurações do módulo sendo setadas corretamente, mas a pasta no template não foi criada.

**Comment by esilvajr** [comment]
Olá. Tente executar o comando magento setup:static-content:deploy pt_BR*

*Se sua loja estiver em um pacote de linguagem diferente do pt_BR substitua esse parâmetro pelo equivalente da linguagem vigente.

**Comment by nadinycostacurta** [comment]
Muito obrigada, funcionou!

**Comment by esilvajr** [comment]
De nada. Qualquer dúvida estamos a disposição...
