### ISSUE TITLE
Alteração na tag

### ISSUE THREAD

**Issue by lcsbaroni** [pagseguro/magento2#63]
Quando os pull requests estão sendo mergeados, vocês estão criando uma nova tag?

**Comment by gabriellucius** [comment]
No geral nós não criamos uma nova tag para um novo PR aceito, pois temos um ciclo de entregas a ser cumprido antes de liberamos um novo pacote: fazemos algumas validações posteriores mesmo depois de testar e aceitar o PR. Daí passamos da branch de desenvolvimento para master se estiver tudo OK, e aí validamos o módulo todo a partir da master e aí formalizamos um novo pacote com novas funcionalidades, correções e PRs mergeados através de uma nova release com uma nova tag.

**Comment by lcsbaroni** [comment]
Entendi. Então é seguro usar no composer:
"pagseguro/magento2": "dev-master" ?

**Comment by gabriellucius** [comment]
É sim, contudo, o ideal seria usar as releases que são os lançamentos oficiais das atualizações do módulo.

**Comment by lcsbaroni** [comment]
Obrigado @gabriellucius ! Só mais uma dúvida, na tag 2.0 o ultimo commit foi o ano passado.
Ela está sendo evoluída? Parece que a tag 1.3 é a mais confiável.

**Comment by gabriellucius** [comment]
Desculpe a demora, mas é isso mesmo, a 2.0.0 foi um erro de nomeclatura que corrigimos depois. O ideal é  usar a tag mais recente (inclusive o próprio git marca ela com uma tag de *Latest Release*

**Comment by lcsbaroni** [comment]
@gabriellucius Obrigado!
