### ISSUE TITLE
PagSeguro não altera forma de pagamento.

### ISSUE THREAD

**Issue by uileprojecttus** [pagseguro/magento2#67]
Olá amigos, 

Estou tendo um problema com o Pagseguro, utilizo o tema Porto, e todo o Javascript está unificado. 
Quando eu tiro o 'merge' do javascript, o módulo funciona corretamente, porém meu tema fica desconfigurado, não carrega alguns arquivos de javascript na homepage. Aí tenho que usar sempre o Javascript unificado. Porém quando faço isso, o módulo pagseguro não responde a troca de modalidade de pagamento. 

URL do site: https://www.woomstore.com

Tentei debugar os erros mas não cheguei a uma saída.

**Comment by uileprojecttus** [comment]
Complementando:

Descobri que o Pagseguro funciona até adicionar algum produto ao carrinho. Acessando a URL diretamente, ela funciona normalmente: https://www.woomstore.com/pt_br/pagseguro/direct/payment/#credit-card

Porém ao adicionar um produto ao carrinho, ele para de funcionar. Ainda não sei o porquê.

**Comment by ghost** [comment]
@uileprojecttus Seu problema foi resolvido ? Foi lançado uma nova versão do plugin do Pagseguro para o Módulo, verifique por favor se o problema foi solucionado ?

**Comment by uileprojecttus** [comment]
Olá, o projeto foi descontinuado.
