### ISSUE TITLE
Undefined property: stdClass::$payment_type on payment success page

### ISSUE THREAD

**Issue by ashishraj-cipl** [pagseguro/magento2#68]
I am facing below issue after successful come back from sandbox pagseguro payment to success page .../pagseguro/direct/success and then refresh the page.
Please look into the issue  and help to resolve.

@pagseguromaster 

a:4:{i:0;s:159:"Notice: Undefined property: stdClass::$payment_type in .../vendor/pagseguro/magento2/Controller/Direct/Success.php on line 102";i:1;s:11002:"#0 .../vendor/pagseguro/magento2/Controller/Direct/Success.php(102): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '...', 102, Array)
#1 .../vendor/pagseguro/magento2/Controller/Direct/Success.php(61): UOL\PagSeguro\Controller\Direct\Success->type()
#2 .../var/generation/UOL/PagSeguro/Controller/Direct/Success/Interceptor.php(24): UOL\PagSeguro\Controller\Direct\Success->execute()
#3 .../vendor/magento/framework/App/Action/Action.php(102): UOL\PagSeguro\Controller\Direct\Success\Interceptor->execute()
#4 .../vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 .../vendor/magento/framework/Interception/Chain/Chain.php(70): UOL\PagSeguro\Controller\Direct\Success\Interceptor->___callParent('dispatch', Array)
#6 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('UOL\\PagSeguro\\C...', 'dispatch', Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Array, 'customer-app-ac...')
#7 .../vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#8 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('UOL\\PagSeguro\\C...', 'dispatch', Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Array, 'contextPlugin')
#10 .../vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('UOL\\PagSeguro\\C...', 'dispatch', Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Array, 'storeCheck')
#13 .../vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('UOL\\PagSeguro\\C...', 'dispatch', Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Array, 'tax-app-action-...')
#16 .../vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(110): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('UOL\\PagSeguro\\C...', 'dispatch', Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Array, 'weee-app-action...')
#19 .../vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): UOL\PagSeguro\Controller\Direct\Success\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 .../vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(UOL\PagSeguro\Controller\Direct\Success\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 .../var/generation/UOL/PagSeguro/Controller/Direct/Success/Interceptor.php(39): UOL\PagSeguro\Controller\Direct\Success\Interceptor->___callPlugins('dispatch', Array, Array)
#22 .../vendor/magento/framework/App/FrontController.php(55): UOL\PagSeguro\Controller\Direct\Success\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 .../vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 .../vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#26 .../vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#27 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 .../vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#32 .../vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 .../vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 .../vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#35 .../vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 .../app/code/TemplateMonster/SiteMaintenance/Model/PageCache/App/FrontController/BuiltinPlugin.php(30): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 .../vendor/magento/framework/Interception/Chain/Chain.php(67): TemplateMonster\SiteMaintenance\Model\PageCache\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 .../vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'switcher-app-ac...')
#39 .../app/code/TemplateMonster/LayoutSwitcher/Model/App/Action/ContextPlugin.php(40): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 .../vendor/magento/framework/Interception/Interceptor.php(142): TemplateMonster\LayoutSwitcher\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 .../var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#42 .../vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 .../vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#44 .../index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#45 {main}";s:3:"url";s:25:"/pagseguro/direct/success";s:11:"script_name";s:10:"/index.php";}

**Comment by ghost** [comment]
@ashishraj-cipl Hello, I did the test according to the description of the above error and I had no problems with the sandbox, sometimes the sandbox goes through weekly maintenance and may have caused this error. A new update of PagSeguro Integration Module for Magento 2.x has been released. Please, please do the test with this new version of the current Github pagseguro.
