### ISSUE TITLE
Erro de validação nos campos de endereço

### ISSUE THREAD

**Issue by Renato-Berg** [pagseguro/magento2#69]
Olá,

Hoje fiquei testando o módulo do PagSeguro e percebi que ele tem uns erros de validação no campo de endereço, sendo que por causa destes erros exibe uma mensagem genérica para o cliente e o mesmo pensa que o erro vai acontecer pra todo mundo, que o site não está funcionando, etc...
No campo endereço, o módulo considera que no primeiro input terá a "Rua" + "," + "Número". Se o cliente digitar algo a mais após o número irá gerar o erro!
E no segundo input do endereço não pode contem mais de 41 caracteres.
Qual é a melhor forma de resolver isso pra ficar genérico e não alterar as configurações padrões do magento?
Obrigado.

**Comment by ghost** [comment]
@Renato-Berg Olá foi lançado uma nova versão do plugin no Módulo de integração PagSeguro para Magento 2.x, verifique se corrigiu o problema de validação dos campos de endereço.
