### ISSUE TITLE
Como configurar retorno?

### ISSUE THREAD

**Issue by pfgianoto** [pagseguro/magento2#70]
boa tarde!
Gostaria de saber como configuro esses dois campos (ver print: http://prntscr.com/fxbdcd ) no módulo?

grato!

**Comment by ramonvic** [comment]
A url de redirecionamento, não sei ao certo qual seria ( utilizo o checkout transparente então é desnecessária) agora a url de notificação é 

`HOST/pagseguro/notification/response`

Essa é a rota que o módulo cria para receber as atualizações de pagamentos.

**Comment by pfgianoto** [comment]
fala Ramon!! cara, muito obrigado! ja me ajudou muito.

**Comment by saulfm08** [comment]
O meu eu coloco mas da página não encontrada
https://importadosdamay.com.br/pagseguro/notification/response

**Comment by ramonvic** [comment]
@saulfm08 Pelo que vi, esse erro 404 não é à nível da aplicação, é servidor, por algum acaso não existe alguma pasta pagseguro dentro da pasta raiz do seu servidor nao? ou alguma regra no webserver que trata o path /pagseguro diferente dos demais? 
É só um chute, mais creio que pode ser por ai o problema.

**Comment by saulfm08** [comment]
Olá @ramonvic , eu procurei por uma pasta pagseguro no root directory do meu servidor porem não encontrei... Quanto a rotas creio que não seja porque eu não mexi em rotas.

Pior que eu nem sei quando foi que parou de funcionar.

Nem o sandbox funciona mais... após selecionar a forma pagseguro de pagamento ele cai na página de 404

**Comment by saulfm08** [comment]
@ramonvic 
Resolvi da seguinte maneira:
`php bin/magento module:uninstall UOL_PagSeguro --clear-static-content`
`rm -rf vendor/pagseguro`
`composer clear-cache`
`composer require pagseguro/magento2`
`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy pt_BR`

Agora está 100% funcional, aproveitei para retirar um backup!

**Comment by ghost** [comment]
@pfgianoto Desculpe a demora na resposta ao seu problema, espero que seu problema tenha sido resolvido e esteja 100% ok ! Foi lançada uma nova atualização do plugin Módulo de integração PagSeguro para Magento 2.x., caso esteja com erro, solicito que teste com essa nova atualização.
