### ISSUE TITLE
Erro 500 ao finalizar pagamento

### ISSUE THREAD

**Issue by goncalocruz77** [pagseguro/magento2#71]
Boa noite, deixei uma dúvida no pagseguro, alguém poderia me ajudar a resolver?
Segue link: https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/115000544554-Pagseguro-para-magento-2-1-dando-erro-ao-finalizar-compra?page=1#community_comment_115000315214
Obrigado.

**Comment by ghost** [comment]
@goncalocruz77 Olá fiz a simulação com o Magento 2.1.9 e não exibiu erros na finalização da compra em nenhum Checkout Padrão, Lightbox ou Transparente, possui uma nova atualização lançada hj no Github, teste com ela novamente.
