### ISSUE TITLE
Frete grátis não funciona com o módulo

### ISSUE THREAD

**Issue by pfgianoto** [pagseguro/magento2#73]
Boa tarde pessoal! outro problema que me deparei com este módulo é que quando criamos uma regra de frete gratis no magento, no pagseguro ele continua a enviar o valor do frete como se o mesmo não fosse gratis. veja nas telas:

![captura de tela 2017-08-11 as 17 30 18](https://user-images.githubusercontent.com/9287243/29231345-e13d68f2-7eb4-11e7-813e-7fff5a872321.jpg)
![captura de tela 2017-08-11 as 17 31 37](https://user-images.githubusercontent.com/9287243/29231346-e141bd62-7eb4-11e7-8995-5173afc26498.jpg)

No log do pagseguro ele esta enviando o valor do frete: http://prntscr.com/g7dz5q 

Alguma ajuda? isso ocorre com voces também?

**Comment by ghost** [comment]
@pfgianoto  Olá simulei o erro descrito acima no Magento 2.x e não está calculando o frete no preço total final no Pagseguro. Foi lançado uma nova versão do Plugin do Módulo de integração PagSeguro para Magento 2.x, teste com essa nova atualização por favor !
