### ISSUE TITLE
3 opcoess de pagamento direto no form

### ISSUE THREAD

**Issue by marcelowu** [pagseguro/magento2#74]
ola, como faco para coloca as 3 opcoess de pagamento direto no form...
sem precisa clica finalizar (Com o PagSeguro, você pode escolher como quer pagar e ainda parcelar sua compra em até 18x)
Ex: 
boleto
debito
credito

**Comment by marcelowu** [comment]
porque quando eu clico no botao finalizar, o carrinho ja fica vazio mesmo sem efetuar os pagamento, dai os mails ja chega para mim..

**Comment by ghost** [comment]
@marcelowu Foi solucionado seu problema ? Foi lançado uma nova versão do plugin do Pagseguro para o Módulo, verifique se o problema foi solucionado!
