### ISSUE TITLE
PagSeguro não considera o endereço de cobrança?

### ISSUE THREAD

**Issue by glaucomorais** [pagseguro/magento2#75]
Estou tendo problemas com o PagSeguro quanto ao endereço de cobrança.

Em uma loja que estou trabalhando há uma lista de casamento que permite o cliente enviar o presente diretamente para o presenteado. O endereço de cobrança é corretamente configurado no pedido do Magento, porém o módulo só envia o endereço de entrega e desconsidera o endereço de cobrança.

Isso é um recurso ou um bug?

**Comment by ghost** [comment]
@glaucomorais Foi lançado uma nova versão do plugin do Pagseugor para o módulo há 14 dias, verifique se o problema foi solucionado ?
