### ISSUE TITLE
Problema com setup:di:compile

### ISSUE THREAD

**Issue by hansbonini** [pagseguro/magento2#76]
Ao utilizar o comando
```
php bin/magento setup:di:compile
```
após instalar o módulo, a presença do seguinte conflito impede o restante da ação:
```
Fatal error:  Cannot use PagSeguro\Domains\Requests\Payment as Payment because the name is already in use in /var/www/html/magento/vendor/pagseguro/magento2/Model/PaymentMethod.php on line 26
```

**Comment by saulfm08** [comment]
@hansbonini porque está tendo que executar o setup:di ? normalmente após a instalação de acordo com as instruções aqui do site não precisa ser feito  mais nada.

**Comment by ghost** [comment]
@hansbonini Olá após instalar o módulo não é necessário utilizar esse comando, oriento a seguir as instruções do link: https://github.com/pagseguro/magento2 para uma instalação correta sem erros e conflitos.
