### ISSUE TITLE
Erro no PagSeguro no envio de dados

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#77]
Olá, 
Hoje ocorreu um erro estranho no PagSeguro. Um cliente estava fazendo checkout, usando o email dele e eu estava fazendo um checkout simultâneo para orientá-lo, usando os meus dados. Quando abriu a minha lightbox do PagSeguro, apesar de eu ter informado os meus dados, a lightbox me informou os dados dele. Nome, email, endereço etc. 

Como resolver isso?

**Comment by ghost** [comment]
@gcampedelli Olá foi lançada uma nova versão do plugin Módulo de integração PagSeguro para Magento 2.x verifique se foi corrigido esse erro descrito.
