### ISSUE TITLE
senderName invalid value

### ISSUE THREAD

**Issue by saulfm08** [pagseguro/magento2#78]
Olá, gostaria de saber como (e onde) corrigir o erro quando uma pessoa informa um nome fora do padrão, como por exemplo informa com dois espaços. Exemplo do erro:

`02/09/2017 19:50:33 PagSeguro.Session[error]: <?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?><errors><error><code>11012</code><message>`**senderName invalid value**`: Nome  Da Pessoa DE CLIENTE </message></error></errors>`

Eu descobri que esse erro ocorre sempre que o nome do comprador é diferente do padrão estabelecido pelo PagSeguro, que é Nome + sobrenome, sem espaços duplicados e obrigatoriamente deve ter apenas letras e espaços, nada de números, o que é até coerente, desde que seu sistema esteja preparado para isso.

Não consegui encontrar onde deve editar, quais arquivos, para resolver isso

**Comment by saulfm08** [comment]
Consegui resolver editando o arquivo 
`vendor/pagseguro/magento2/Model/PaymentMethod.php`

Alterando a linha 141 para o seguinte:
`$senderName = trim($address->getFirstname()) . ' ' . trim($address->getLastname());`

Funcionou perfeitamente para remover os espaços

**Comment by diegolhambi** [comment]
Tive esse problema também de sanitização das variáveis inseridas pelo usuário, não somente essa mas outras variáveis não são realizadas nenhum tipo de tratamento pra evitar espaços indevidos ou alguma coisa que não seja aceito pela API.

**Comment by ghost** [comment]
@saulfm08 @diegolhambi OLá foi lançada uma nova versão do Plugin do Módulo de integração PagSeguro para Magento 2.x 26/12/2017, verifique se foi corrigido esse erro.
