### ISSUE TITLE
Checkout Transparente Failure

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#79]
Caros:

Eu não sei o que acontece, mas o PAG SEGURO diz que o Checkout transparente está habilitado na minha conta e toda vez que eu processo pagamento dá failure. Alguém sabe me dizer o por quê? No Lightbox, o campo de telefone retorna com erro às vezes e eu tirei o campo de telefone do checkout para funcionar. Seria isso? O que pode ser? Alguém poderia dar uma luz, por favor?

**Comment by ghost** [comment]
Olá @gcampedelli foi publicada uma nova versão do Plugin do Módulo de integração PagSeguro para Magento 2.x 26/12/2017, verifique se corrigiu seu problema !
