### ISSUE TITLE
Erro no Checkout transparente

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#80]
Recebo esse erro no console

XML Parsing Error: no root element found
Location: https://dna.uol.com.br/service/cookie?_=n.0 cookie
Line Number 1, Column 1:

**Comment by gcampedelli** [comment]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]  pagseguro.mediator.directpayment.1504114902696.js:1:11310
	PagSeguro.APIMediator/this.acceptMessage/callbacks[callbacks.length] https://stc.pagseguro.uol.com.br/pagseguro/j/pagescripts/checkout/direct-payment/pagseguro.mediator.directpayment.1504114902696.js:1:11310

**Comment by ghost** [comment]
@gcampedelli Pode me passar mais detalhes do erro, em que momento acontece. Esse erro é frequente ? Conseguiu solucionar seu problema ?

**Comment by gcampedelli** [comment]
Olá Felipe Branco, a maioria dos erros foram solucionados. 
Na verdade, foi verificado que o checkout transparente não aceita o checkout sem que o consumidor esteja logado na conta. Desse modo, é impossível o checkout como guest e vários erros aparecem nos logs, esse que está mencionado inclusive. 
A minha solução foi mudar o checkout do Magento 2, usando um javascript que verifica primeiro se o consumidor já é cadastrado no site usando o email fornecido por ele. 
Daí para frente:
a) Se o consumidor já é cadastrado -> Pop-up pede para que ele faça login
b) Se o consumidor não é cadastrado -> Pop-up pede para ele criar uma senha e já loga o consumidor
c) O consumidor fornece os demais dados, ao pressionar o botão, ele é redirecionado já logado para o formulário do checkout transparente. 
d) Se ele fornecer os dados do cartão corretamente, ele obtém sucesso na compra. 
Ainda existe um descontentamento da minha parte com o módulo PagSeguro para Magento 2 e se refere justamente ao fato de que eu gostaria que o consumidor mudasse de página apenas no sucesso da compra. 
Hoje o flow está da maneira acima, ou seja, depois de apertar o botão de pagamento, ele é redirecionado ao formulário para fornecer os dados do cartão. 
Eu gostaria que o formulário para fornecer os dados do cartão já estivesse disponível quando ele seleciona o PagSeguro como meio de pagamento, no passo payment methods. E, ao apertar o botão, posto que ele já está logado (e aqui seria uma boa ideia permitir o guest checkout também), os dados são enviados, sem a necessidade de um terceiro redirecionamento. 
A outra questão é a seguinte. Para tanto, seria uma boa ideia implementar o card.js ( https://github.com/jessepollak/card) já no método de pagamento. No caso do Magento 2 sem personalização é no segundo passo, "payment methods".  
Um outro bom exemplo de módulo onde o formulário de cartão ja aparece nos métodos de pagamento, quando o método é selecionado é o Paymentwall, mas infelizmente, esse layout não está disponível para PagSeguro, apenas para o método Brick. No caso deles, o formulário não é um phtml, como no caso do PagSeguro, mas está diretamente implementado no payment.html, ou seja, no knockout. 
Por hora são essas as minhas sugestões. Se o PagSeguro não puder implementar o Guest Checkout para o método transparente, eu sugiro que vocês criem um login com o PagSeguro, permitindo o consumidor logar na loja com as credenciais do PagSeguro, o que seria uma boa ideia também . 
Espero ter contribuído com a solução e, caso seja necessário, existem muitas informações de debug fórum do PagSeguro do próprio UOL.

**Comment by ghost** [comment]
@gcampedelli Em relação a primeira sugestão hoje no Checkout transparente, ao escolher essa opção no Admin e dentro da loja quando o usuário escolhe o meio de pagamento Pagseguro, o sistema exibe as opções de Cartão de Crédito, Boleto ou Débito Online no passo payment methods. Poderia verificar na última versão essa sugestão está implementada no Checkout Transparente

Suas sugestões são sempre bem vindas ao Pagseguro, irei passar para a Equipe de Desenvolvimento do Pagseguro analisar a segunda questão seguredia para possível implementação no plugin do Módulo Magento 2. Fique á vontade sempre para oferecer novas sugestões ao Pagseguro.
