### ISSUE TITLE
Suporte ao Magento 2.2+ Release Candidate

### ISSUE THREAD

**Issue by diegosanfelix** [pagseguro/magento2#82]
Ao tentar instalar via Composer, o módulo não instala por ainda não ter suporte ao PHP 7.1+, requisito mínimo do Magento 2.2+.

**Comment by ghost** [comment]
@diegosanfelix Irei passar á equipe de Desenvolvimento do Pagseguro esse problema enfrentado por você para análise e possível correção.

**Comment by gabriellucius** [comment]
Olá @diegosanfelix 

A versão final do Magento 2.2 suporta outras versões do PHP além da 7.1+, conforme a [documentação](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html), e o print abaixo:

![image](https://user-images.githubusercontent.com/8374748/34773911-7c009f6a-f5f4-11e7-978e-2a57e5974b6d.png)

Quanto à compatibilidade do módulo com o PHP 7.1+ ainda precisamos validar.

Como a versão não é mais um problema, iremos fechar a issue.
Obrigado pela contribuição.
