### ISSUE TITLE
Algumas dúvidas - Magento 2.1.0

### ISSUE THREAD

**Issue by index325** [pagseguro/magento2#83]
Tenho um e-commerce desenvolvido em Magento 2.1.0. Preciso saber se existe a possibilidade de serem executadas algumas tarefas e verificações no pagamento. É possível executá-las? Se sim, como?

1:
Poder escolher o desconto por produto ou grupo de produto.
Exemplo: Toda linha de um produto específico em 10% de desconto nas compras a vista

2:
Poder definir um grupo de produtos que aceita parcelamento e outro não
Exemplo: Não aceita parcelamento na compra de produtos de aço

3:
Poder fixar o valor de desconto em 10% para compras  pagas com boleto. Hoje é 14,65%

4:
Escolher um desconto diferente para um mesmo produto dessa forma:
Pagando à vista tem um desconto
Pagando em 5x tem outro desconto
Pagando em 10X tem outro desconto

Exemplo:
864 à vista
972 em 5x
1080 em 10x

Aguardo resposta !

**Comment by ghost** [comment]
@index325 Referente as dúvidas. As dúvidas seriam referentes ao módulo Magento ou referente ao plugin do Pagseguro para magento 2x ?

1) No Magento 2x, tem a opção para configurar para poder escolher o desconto por produto ou grupo de produto.
2) Não possui essa opção no módulo Magento 2x.
3) É possível pelo PagSeguro, mas não possui essa opção no módulo do Magento 2x.
4) Não possui essa opção no módulo Magento 2x
