### ISSUE TITLE
PHP 7.1+

### ISSUE THREAD

**Issue by luizpaulofranz** [pagseguro/magento2#84]
Tem como atualizar as versões possíveis no composer? As versões mais recentes do PHP não são suportadas pelo módulo devido a configuração no json.

**Comment by fabcardoso40** [comment]
Estou enfrentando o mesmo problema. Se você souber como resolver manda um post.

valeu!

**Comment by luizpaulofranz** [comment]
Olá, uma solução provisória é forçar o composer a ignorar essa verificação, adicionando "--ignore-platform-reqs". Você coloca essa dependencia no seu composer.json e roda o comando:
`composer update --ignore-platform-reqs`, ou um fork no projeto e altera direto no composer.json.

**Comment by ghost** [comment]
@luizpaulofranz @fabcardoso40 Iremos disponibilizar, mas ainda não temos uma previsão de data =/
