### ISSUE TITLE
Magento 2 bug, correção e direct checkout

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#85]
Caros, vou descrever o problema e vamos ver se existe solução possível porque afeta o PagSeguro. 

O Magento 2 tem um bug:

"Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "seu site" from accessing a cross-origin frame."

A correção oficial do Magento 2 é essa aqui: https://github.com/magento/magento2/blob/2.1.10-preview/app/code/Magento/PageCache/view/frontend/web/js/page-cache.js#L30

Ou alguma variação desse código (eu testei todas) em page-cache.js. 

A solução apresentada por eles realmente resolve o problema em todos os browser, mas quebra o Jquery do redirect checkout do PagSeguro. 

Existe alguma solução possível do time técnico do PagSeguro para resolver essa quebra e podermos usar a solução do Magento 2 para não obter o erro de iframe de terceiros?

**Comment by ghost** [comment]
Olá @gcampedelli foi lançado uma nova versão do plugin do pagseguro no link: https://github.com/pagseguro/magento2/tree/desenvolvimento, verifique se corrigiu a quebra do Jquery do redirect checkout do Pagseguro!
