### ISSUE TITLE
main.CRITICAL: Payment model name is not provided in config!

### ISSUE THREAD

**Issue by mageuser** [pagseguro/magento2#93]
Módulo não funcionando na versão magento 2.2.2

**Comment by ghost** [comment]
@kauansoft Damos suporte nas versões do Magento Community 2.0.8 | 2.1.0 até a versão 2.1.9, estamos fazendo uma readequação do módulo para dar suporte na versão magento 2.2.2 e iremos disponibilizar em breve a versão do plugin.

**Comment by mageuser** [comment]
@felipebranco Você tem uma previsão? Pois colocarei o site em produção brevemente, já estou negociando com a cielo que está pronta para essa versão 😃

**Comment by ghost** [comment]
Olá @kauansoft Iremos disponibilizar em breve, mas não temos uma previsão de data =/

**Comment by gcampedelli** [comment]
Tô com o mesmo problema no 2.2.2. Essa inconsistência acontece no checkout do IWD. Aliás, a primeira inconsistência é no próprio admin quando diz que a label é inválida. Depois no checkout.

**Comment by gcampedelli** [comment]
é alguma coisa no config.xml. Alguém tem a solução??

**Comment by mageuser** [comment]
Estou usando o moip

Em qua, 14 de mar de 2018 às 14:39, gcampedelli <notifications@github.com>
escreveu:

**Comment by gcampedelli** [comment]
Fiz de tudo e o jeito vai ser mudar para o Moip. Seria legal o pag seguro resolver mais esse bug rapidamente.

**Comment by mageuser** [comment]
O moip me respondeu em 2 minutos, entraram no meu painel e corrigiram
tudo e ainda me deram dicas 👍

Em qua, 14 de mar de 2018 às 14:55, gcampedelli <notifications@github.com>
escreveu:

**Comment by gcampedelli** [comment]
Vou testar o Moip. O Pag Seguro sempre me atendeu. Acho bizarro o suporte aqui estar parado e só nós conversarmos. Eles conseguiram um investimento alto no exterior. Podiam desfocar da Moderninha e focar um pouco nisso aqui. O Magento 2 está evoluindo muito e, com esse investimento, eles poderiam estar na frente.

**Comment by mageuser** [comment]
Verdade, e esqueci de comentar, consegui menores taxas que a do pagseguro.

Em qua, 14 de mar de 2018 às 15:04, gcampedelli <notifications@github.com>
escreveu:

**Comment by gcampedelli** [comment]
Eu ainda tenho uns 8 pull requests abertos. Queria alguém da comunidade Magento 2 para trocar uma figurinhas e uns módulos. De bug em bug eu fiquei expert.

**Comment by mageuser** [comment]
Bacana, podemos conversar mais, meu email : 3kauan@gmail.com.

Em qua, 14 de mar de 2018 às 15:08, gcampedelli <notifications@github.com>
escreveu:

**Comment by gabriellucius** [comment]
Pessoal, temos previsão de lançar uma versão nova do Módulo com suporte para Magento 2.2.2 para o início de Abril.

Quanto aos PRs vamos trabalhar na validação/aceite em paralelo na medida do possível durante essa entrega.

**Comment by gcampedelli** [comment]
Obrigada Gabriel. 
Gostaria de mencionar que eu consegui o PagSeguro funcionando no checkout 2.2.2. Não testei ainda no 2.2.3. A grande questão é que ele é incompatível com o IWD, tem algo no config.xml, alguma inconsistência que faz com que ele quebre o módulo no admin. No mais, quando eu migrei de servidor, com a mesma configuração, o checkout parou de conversar com o PagSeguro. Não consigo entender o motivo. Apareceram erros que nunca vi. E com o Mageplaza OSC, o PagSeguro também teve algumas inconsistências que não estavam presentes no 2.1.9.

**Comment by tamims87** [comment]
Olá, Gabriel! Atualizei o módulo essa semana mas continua sem funcionar, aqui no GIT ainda está a informação sobre ser testado até a versão 2.1.9... temos uma nova previsão? Obrigada!
