### ISSUE TITLE
Tutorial de Instalação - Vídeo Aula

### ISSUE THREAD

**Issue by arielcugenotta** [pagseguro/magento2#94]
Oi Pessoal,

Eu fiz um vídeo sobre como instalar o modulo do PagSeguro no Magento 2:
https://youtu.be/4LDnjLx9KTc

Espero que ajude!

**Comment by ghost** [comment]
@arielcugenotta Obrigado pela contribuição de disponibilizar um vídeo de instalação do plugin do módulo do Pagseguro no Magento 2.
