### ISSUE TITLE
Problemas na novas versão do PagSeguro para Magento 2 

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#96]
Erros em di:compile

Errors during compilation:
	UOL\PagSeguro\Model\Transactions\Methods\Cancellation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Cancellation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Cancellation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Refund
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Refund in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Refund.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Conciliation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Conciliation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Conciliation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Abandoned
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Abandoned in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Abandoned.php
\Magento\Framework\App\ResourceConnection already exists in context object
Total Errors Count: 4
Errors during compilation:
	UOL\PagSeguro\Model\Transactions\Methods\Cancellation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Cancellation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Cancellation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Refund
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Refund in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Refund.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Conciliation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Conciliation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Conciliation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Abandoned
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Abandoned in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Abandoned.php
\Magento\Framework\App\ResourceConnection already exists in context object
Total Errors Count: 4
Errors during compilation:
	UOL\PagSeguro\Model\Transactions\Methods\Cancellation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Cancellation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Cancellation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Refund
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Refund in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Refund.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Conciliation
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Conciliation in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Conciliation.php
\Magento\Framework\App\ResourceConnection already exists in context object
	UOL\PagSeguro\Model\Transactions\Methods\Abandoned
		Incorrect dependency in class UOL\PagSeguro\Model\Transactions\Methods\Abandoned in /var/www/html/magento2/vendor/pagseguro/magento2/Model/Transactions/Methods/Abandoned.php
\Magento\Framework\App\ResourceConnection already exists in context object
Total Errors Count: 4

Erros no console do Chrome

Erros no Chrome
Failed to load resource: the server responded with a status of 404 (Not Found)
dna.uol.com.br/service/etag Failed to load resource: the server responded with a status of 412 (Precondition Failed)
pagseguro.uol.com.br/checkout/direct-payment/i-ck.html#rmcl:1 Uncaught SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at callbacks.(anonymous function) (https://stc.pagseguro.uol.com.br/pagseguro/j/pagescripts/checkout/direct-payment/pagseguro.mediator.directpayment.1519241151227.js:1:11315)
3pagseguro.uol.com.br/checkout/direct-payment/i-ck.html#rmcl:1 Uncaught SyntaxError: Unexpected token _ in JSON at position 0
    at JSON.parse (<anonymous>)
    at callbacks.(anonymous function) (https://stc.pagseguro.uol.com.br/pagseguro/j/pagescripts/checkout/direct-payment/pagseguro.mediator.directpayment.1519241151227.js:1:11315)

Erros no console do firefox

XML Parsing Error: no root element found
Location: https://dna.uol.com.br/service/cookie?_=1519384948767
Line Number 1, Column 1:
cookie:1:1
XML Parsing Error: no root element found
Location: https://dna.uol.com.br/service/etag
Line Number 1, Column 1:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
[Learn More]

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
[Learn More]
pagseguro.mediator.directpayment.1519241151227.js:1:11310
NS_ERROR_FAILURE: 
dna.min.js:4
ReferenceError: event is not defined

Resultado, direct checkout não funciona.

**Comment by gcampedelli** [comment]
Quanto ao di:compile, é preciso que o módulo comente as linhas \Magento\Framework\App\ResourceConnection nos respectivos arquivos que apresentam erro. 
Com isso, o módulo funciona no checkout no Chrome com algumas issues, por exemplo, sem a validação dos dados do cartão, deixando que as mensagens MageError apareçam e não sumam. 
No Firefox continua tudo errado. Vários erros no console, o campo de preenchimento do cartão não aceita input etc. 
Ainda não testei no Safari, mas se vocês tiveram alguma dica, seria ótima deixar tudo funcionando nessa última versão.

**Comment by lcsbaroni** [comment]
É importante ao lançar uma versão nova, garantir que os comandos abaixo estejam rodando corretamente:
php bin/magento setup:di:compile
php bin/magento deploy:mode:set production

Esses comandos que compilam as classes e geram todo o conteudo da loja para todos os idiomas.
