### ISSUE TITLE
Não deixa deletar número no input

### ISSUE THREAD

**Issue by gcampedelli** [pagseguro/magento2#97]
Olá, depois de umas alterações, o que eu consegui:

1) Resolver o problema do di, comentando as linhas que estavam gerando erro e não são necessárias no código
2) Resolver o problema do firefox que não deixava inserir o número do cartão, declarando event nas funções presentes no JS
3) Resolver o problema do erro na validação que dispara mesmo se o input está correto. 

Mas, agora, eu encontro erro na hora de deletar caracteres do formulário do cartão. Alguém sabe resolver esse problema com a input mask? O resto todo está funcionando.

**Comment by mageuser** [comment]
Qual a versão do seu Magento?

**Comment by gcampedelli** [comment]
A versão é 2.1.9. Não deixa apagar o cartão se errar a digitação. Você tem um fix pra isso? Agradeço!
